### ISSUE TITLE
Flatpak Package?

### ISSUE THREAD

**Issue by imbev** [aandrew-me/ytDownloader#1]
Could a Flatpak package be distributed?

**Comment by aandrew-me** [comment]
Most likely, I will try.

**Comment by aandrew-me** [comment]
Flatpak package has been added in the latest update. Please check and let me know.

**Comment by imbev** [comment]
The flatpak package works perfectly. If you want to publish your app to flathub, see https://github.com/flathub/flathub/wiki/App-Submission .

**Comment by aandrew-me** [comment]
Great that it works. 

I have gone through Flathub's documentation on building flatpaks and it's a bit of a hasstle. I need some time to understand how to prepare the app for Flathub.

And, thanks for the feedbacks!

**Comment by aandrew-me** [comment]
I finally added the app to flathub.

https://flathub.org/apps/details/me.aandrew.ytdownloader
