### ISSUE TITLE
Download Playlist option forces .webm format and separate audio files

### ISSUE THREAD

**Issue by micah-raney** [aandrew-me/ytDownloader#101]
Unlike when trying to download a single video, in playlist mode, ytDownloader does not allow for selecting different video formats and seems to save everything as a .webm. It also splits the audio and video files. Downloading the videos individually does not do this. Not sure if this is a bug or if I'm overlooking something very simple. Please advise.

Using AUR version 3.10.5-1 on Manjaro

**Comment by aandrew-me** [comment]
Hey! Thanks for reporting.

It's actually a bug. But its only present in the AUR version. I will fix it. In the meantime you can use the flatpak/snap/appimage version.

**Comment by aandrew-me** [comment]
And regarding .webm, it should download mp4 next update onwards

**Comment by micah-raney** [comment]
Thank you much
