### ISSUE TITLE
Some error has occurred. Check your network and use correct URL

### ISSUE THREAD

**Issue by PaulGWolfson** [aandrew-me/ytDownloader#102]
The following error occurs on Ubuntu Linux 22.04 "Some error has occurred. Check your network and use correct URL" when pasting a URL from Youtube using the Chrome Browser.  

![image](https://user-images.githubusercontent.com/62674281/215241235-f126d33a-ab7e-4a87-9db0-cd4c0844c102.png)

Lovely UI but struggling a bit.

**Comment by aandrew-me** [comment]
Hello,
I need some more details.
- Which version you are using (Flatpak/Snap/other)?
- Is it showing error messages with all youtube urls or just this one?
- Please provide the URL

**Comment by PaulGWolfson** [comment]
Sorry I'm not a node.js coder so I'm not going to be much help debugging
the problem.

I installed it from the *snap *store.

***@***.***:/media/pwolf/USB DISK/Public/music$ which ytdownloader
/snap/bin/ytdownloader



> ytDownloader 3.10.6
> ytDownloader lets you download videos and audios from hundreds of sites
> like Youtube, Facebook, Instagram, Tiktok, Twitter and so on

It's a Free and Open Source app built on top of Node.js and Electron.
> yt-dlp has been used for downloading

Source Code is available here


Here is what --help shows.

The error occurs *on all URLs*.  So, it is probably user error or an
installation issue.  Here is an *example link:*  "
https://www.youtube.com/watch?v=EtJcflKZdp0"

If it helps, here is a similar CLI program which works fine:

alias ytdl='yt-dlp --audio-format mp3 -x '
version 2022.11.11



Paul Wolfson
Washington, DC

**Comment by aandrew-me** [comment]
Thanks for the information. And no worries, you don't have to be a developer.

The snap version is working fine for me. I want to take a deeper look into this. Is there a way to personally message you?

**Comment by PaulGWolfson** [comment]
You can text me at +1.202.803.1727 but be warned email is better, I need to
find reading glasses to read the phone.

Paul Wolfson
Washington, DC

**Comment by aandrew-me** [comment]
Ok lets continue here. 

I will need you to open the app. Then open developer tools. You can do that in 2 ways
1. By pressing **Ctrl + Shift + I**
2. From the top menu, select **View** > **Toggle Developer Tools**

Then paste the link in the app. Take a screenshot of the error messages and send it

**Comment by PaulGWolfson** [comment]
The paste event just triggers the usual error message.

[image: image.png]

https://www.youtube.com/watch?v=7FWMBqjxX20

[image: image.png]

ytdl *^[[200~*https://www.youtube.com/watch?v=7FWMBqjxX20*~*

One obvious thing to check is link extraction, on the command line the URL
is escaped.


Paul Wolfson
Washington, DC

**Comment by aandrew-me** [comment]
It would be good if you send your message from Github as your images are not being sent.
Here is what I see
![image](https://user-images.githubusercontent.com/66430340/215278962-8675e1fd-50c9-4849-9951-c05f1e7a38d5.png)

This is the link to the issue where we are having discussion
https://github.com/aandrew-me/ytDownloader/issues/102

**Comment by PaulGWolfson** [comment]
The paste event just triggers the usual error message.

![image](https://user-images.githubusercontent.com/62674281/215279161-6b298b35-b7d1-4c93-a3c6-46202801f2d6.png)


https://www.youtube.com/watch?v=7FWMBqjxX20

![image](https://user-images.githubusercontent.com/62674281/215279202-ccffce29-9ea8-43ac-be6d-825cb118ecdb.png)

ytdl ^[[200~https://www.youtube.com/watch?v=7FWMBqjxX20~

One obvious thing to check is link extraction, on the command line the URL is escaped.

**Comment by aandrew-me** [comment]
Great
Please Select Console mode and then try again
![image](https://user-images.githubusercontent.com/66430340/215279348-bed05703-f007-4470-913a-1a59fc9b845e.png)

**Comment by PaulGWolfson** [comment]
![image](https://user-images.githubusercontent.com/62674281/215279525-182601a2-d338-4d08-adc4-8930e8c36ea7.png)

**Comment by aandrew-me** [comment]
I see.
You have selected Chrome browser to use Cookies from and that is causing problems. You will have to choose **None** there. That option doesn't work properly with Snaps since they isolate the app.

**Comment by PaulGWolfson** [comment]
![image](https://user-images.githubusercontent.com/62674281/215279913-0f07e48a-f810-4b90-b9e4-f335ac1373bb.png)

![image](https://user-images.githubusercontent.com/62674281/215279975-b744c649-1904-4214-a8b4-167a964afbf5.png)

**Comment by aandrew-me** [comment]
Are you using a proper url?

**Comment by PaulGWolfson** [comment]
I don't know.  It's a mouse click on my end.  However in yt-dlp the URL is escaped, which I correct manually.

**Comment by aandrew-me** [comment]
Don't worry about that, just copy the url from browser and click in the app. It should work

**Comment by aandrew-me** [comment]
The log message in your screenshot says that you didn't paste anything
![image](https://user-images.githubusercontent.com/66430340/215281613-09cda545-81cf-4681-bdba-dd85a0615d6d.png)

**Comment by PaulGWolfson** [comment]
Aha!!!

![image](https://user-images.githubusercontent.com/62674281/215281593-75dd3114-3f6a-48f9-944f-c74998100260.png)

**Comment by aandrew-me** [comment]
Great its working fine, you can close the Developer tools now
![image](https://user-images.githubusercontent.com/66430340/215281808-3b60dcd8-5468-4a0e-bb6c-55ba8823bc7b.png)

**Comment by PaulGWolfson** [comment]
May want to throw an exception as the code matures.  Thanks!  Paul

**Comment by aandrew-me** [comment]
I am glad that it's working fine.

I will improve error handling. 

I am closing this issue

**Comment by aandrew-me** [comment]
And if you find the project useful, a star ⭐ would be appreciated!
Have a good day/night!

**Comment by PaulGWolfson** [comment]
Andrew,

;} Thanks for your help.  It *almost* makes me want to learn node, almost.
Simpler is better.  I fondly remember toggling 5 magic instructions from
sense switches of a PDP-12 to talk to the ASR-33 teletype - to talk to the
paper tape reader to load the mag tape reader {...}


Paul Wolfson
Washington, DC
