### ISSUE TITLE
Audio Download NOT working properly 

### ISSUE THREAD

**Issue by frank392a** [aandrew-me/ytDownloader#103]
Using V 3.10.6 Audio Download NOT working properly. Keeps downloading in Webm format

**Comment by aandrew-me** [comment]
I will need some more details.
Which Operating system are you using? Which Audio format are you trying to download?

**Comment by frank392a** [comment]
Hi, I'm using linux Mint the latest and ti Got the same problem on Mp3 and ogg for the other I do not know I have not try it

**Comment by aandrew-me** [comment]
I see.

Which package version are you using (snap/flatpak/appimage)?
And it would be great if you can download a file keeping the Developer tools open.
You can do that by pressing **Ctrl + Shift + I** ,  then select **Console**.
![image](https://user-images.githubusercontent.com/66430340/215308288-0adfa6db-e72a-441d-b4fc-48f79173f2eb.png)

**Comment by frank392a** [comment]
Hi Aandrew, 
I'm using Flatpak.
![error](https://user-images.githubusercontent.com/110358754/215332901-266bbbc3-50cb-4504-bb88-c3c6c60efd01.png)

**Comment by aandrew-me** [comment]
I am very glad that you liked the app. And thanks for your suggestion.

Now what I see in the screenshot is you already have `ffmpeg` installed and that `ffmpeg` is failing to convert audio to the desired format. However I ship a custom `ffmpeg` with the app. So I will make sure that one is being used. 

Let me change some code and I will push an update soon. Let me know after the update if you are still facing the problem.

**Comment by aandrew-me** [comment]
I have pushed an update to flathub. Please check and let me know

**Comment by frank392a** [comment]
It is working perfect now. Thank you so very much!!!

**Comment by aandrew-me** [comment]
Awesome!
