### ISSUE TITLE
Add new awesome engines 

### ISSUE THREAD

**Issue by trimechee** [aandrew-me/ytDownloader#105]
Hello, thank you very much for this great sensational wonderful dowloader !! 💯 

I guess that ytDownloader use the famous yt-dlp, thay's great and my suggestion is in order to download from even more web sites and possibly overcome eventual  yt-dlp bugs and speed up downloads and download torrent, m3u8 files... my suggestion is to add support for these downloader engines if it is technically possible, thank you very much !

https://github.com/nilaoda/N_m3u8DL-CLI

https://github.com/nilaoda/N_m3u8DL-RE

https://github.com/soimort/you-get

https://github.com/iawia002/lux

https://github.com/nilaoda/BBDown

https://github.com/kanishka-linux/hlspy

https://github.com/mikf/gallery-dl

https://aria2.github.io/

https://www.gnu.org/software/wget/

https://github.com/dabaisuv/Tampermonkey-Script
https://greasyfork.org/fr/users/901788-dabaisuv
Unlimited_downloader by dabaisuv
https://greasyfork.org/fr/scripts/445751-unlimited-downloader
https://www.v2ex.com/t/856510

https://github.com/Momo707577045/m3u8-downloader/blob/master/README-EN.md
https://github.com/Momo707577045/media-source-extract

https://github.com/acolwell/mse-tools

*EDIT : I add some new engines : 
hlsdl : C program to download VoD HLS (.m3u8) files, it seems that some people said ffmpeg could have some problems with hls streams...

https://github.com/selsta/hlsdl

and  this software : python  m3u8 Parser for HTTP Live Streaming (HLS) Transmissions :

https://github.com/globocom/m3u8

https://greasyfork.org/en/scripts/25068-downloadallcontent

https://greasyfork.org/en/scripts/7362-true-url-downloads

https://greasyfork.org/en/scripts/22590-easy-offline

https://github.com/dodying/UserJs/tree/master/novel/novelDownloader

https://greasyfork.org/en/users/8227-hoothin

https://github.com/hoothin/UserScripts

https://greasyfork.org/en/scripts/446385-download-any-thing

https://greasyfork.org/fr/scripts/445751-unlimited-downloader

https://github.com/Momo707577045/m3u8-downloader/blob/master/README-EN.md

https://greasyfork.org/en/scripts/18671-inject2download

ArtPlayer.js is a modern and full featured HTML5 video player

https://github.com/zhw2590582/ArtPlayer

https://artplayer.org/

https://www.v2ex.com/t/856510

https://github.com/zhw2590582/bilibili-live-recorder

dabaisuv/Tampermonkey-Script@d109782

https://segmentfault.com/a/1190000025182822

https://github.com/zhw2590582/live-video-study-notes

https://github.com/zhw2590582/FlvPlayer

https://flvplayer.js.org/

***

extensions web browsers downloaders

https://github.com/rowrawer/stream-detector/

https://github.com/meowcateatrat/elephant

https://github.com/FreeDownloadManagerTeam/fdm-addons-docs

https://github.com/inbasic/bulk-media-downloader/

https://github.com/downthemall/downthemall

https://github.com/chandler-stimson/live-stream-downloader

https://github.com/zaidka/cliget

https://github.com/globocom/m3u8

https://github.com/HeiSir2014/M3U8-Downloader

https://github.com/hestyle/m3u8_downloader

https://github.com/kz26/gohls

https://github.com/Last-Order/Minyami

https://github.com/Momo707577045/m3u8-downloader

https://github.com/Momo707577045/media-source-extract

https://github.com/nilaoda/N_m3u8DL-RE

https://github.com/puemos/hls-downloader

https://github.com/Spark-NF/hls-downloader

https://chrome.google.com/webstore/detail/m3u8-finder-and-hls-playe/gijhpnmjcpbddpedmmdihijogkkejfgj?hl=en

https://www.hlsloader.com/

https://github.com/rowrawer/stream-detector

Girdplayer has integrated this software streamlink :
https://github.com/vzhd1701/gridplayer#features 
https://github.com/streamlink/streamlink

**Comment by aandrew-me** [comment]
Hello!
I am glad liked the app. And I appreciate your suggestions.

Adding support for m3u8 and things related to video/audio maybe possible. The only obstacle is that I need to find cross platform solutions. I will try.

Regarding torrents and files, I don't want to add those. There are separate apps for those which do a great job. 
You can check [Motrix](https://motrix.app/)

**Comment by aandrew-me** [comment]
Motrix uses aria2c, so it can download torrents and other files.

Regarding cookies, you can use cookies from other browsers in ytDownloader. Check the preferences. 

yt-dlp supports config file, so I added config file support to ytDownloader too. It can be selected from preferences.

Regarding dailymotion, did you try increasing concurrent fragments? 
yt-dlp has this option
```
-N, --concurrent-fragments N    Number of fragments of a dash/hlsnative
                                video that should be downloaded concurrently
                                (default is 1)
```
Try increasing the value and see if it changes anything

**Comment by aandrew-me** [comment]
Its not for users. Its used by auto updater.

**Comment by trimechee** [comment]
Hello @aandrew-me , i make the confg file file with -N 5 and tried to donwload dailymotion but it fails , i have this message : "URL: https://www.dailymotion.com/video/x8hwc6x

ERROR: [dailymotion] x8hwc6x: Unable to download JSON metadata: (caused by URLError(gaierror(11001, 'getaddrinfo failed')))



but without config file, i can donwload  this dailymotion video but speed  is limited to 70Kb/s !

**Comment by aandrew-me** [comment]
That's disappointing.

**Comment by trimechee** [comment]
I put config file in C: , i will try to put -N 2....for cookies, i choose edge browser, so really ytDownloader can import and use encrypted cookies from famous powerful microsodt edge browser ?

**Comment by aandrew-me** [comment]
yt-dlp uses some library(s) that can decrypt the cookies

**Comment by trimechee** [comment]
Awesome !! 💯

**Comment by trimechee** [comment]
Hello, i edit my first post to add in the end some new engine that seems powerful and to fix bugs when there is ffmpeg bugs : 

C program to download VoD HLS (.m3u8) files, i read that ffmpeg could have some problems with hls streams, so I think it may be a good idea, if this software is compatible with Media-Downloader to integrate it in order to avoid possible bugs with hls streams :

https://github.com/selsta/hlsdl

and also this tool : m3u8 which is Python m3u8 Parser for HTTP Live Streaming (HLS) Transmissions :

https://github.com/globocom/m3u8

The bug : " ......HLSDL appears working much better than ffmpeg in these cases.
Hlsdl is public and the source code available.
The stream plays almost immediately and is stable. No errors or buffering.
Using ffmpeg for the download step gives a very long intial delay and is not very stable.
so I assume that the new crypto+hls RAI flows are badly handled by ffmpeg based players now.....

the video is choppy and unable to buffer enough for a fluid vision. Parole has no problem.

FFmpeg is not good for HLS streams, but I watched a lot of various HLS streams without any problems. The main problem is that FFmpeg downloads all streams (many video sizes at once), so you can watch only HLS stream with single video size"
"

**Comment by trimechee** [comment]
I added also new amazing scripts downloaders and even extensions, may be ytDownloader can verify the code of some of these scripts and extensions and  make native new wonderful  extension specific and compatible with ytDownloader to detect some streaming streams that yt-dlp cant' detect and send the streams to ytDownloader manager to accelerate the donwload ...thank you !

**Comment by aandrew-me** [comment]
Hello.

I really appreciate you trying to help. The thing is I have to ship a different ffmpeg binary for each platform. Adding another executable file will require the same. And the app size is already big, so it will increase the size even more.
That's why I don't want to add more executables to the app. 

However, I was able to to make the downloads of m3u8 videos possible. So that would be available in next update.
