### ISSUE TITLE
[Feature Request] disable built-in auto-update

### ISSUE THREAD

**Issue by soredake** [aandrew-me/ytDownloader#106]
**Description**
It would be nice to have option to disable built-in autoupdate as i use chocolatey for updating ytdownloader.

**Comment by aandrew-me** [comment]
Hello.

When I push updates to chocolatey, they take days to approve and only then push the update. That's why I don't push updates to chocolatey, so the version there is always the same and that's where the auto updates comes to rescue

**Comment by soredake** [comment]
I will prefer to wait cause this way i don't need to do anything, software will be auto-updated, i don't really want to do multiple clicks to update it every time.

**Comment by aandrew-me** [comment]
I will add an option to disable auto updates.

**Comment by soredake** [comment]
Thanks!
