### ISSUE TITLE
Audio Quality and Preferred Audio Quality 

### ISSUE THREAD

**Issue by trimechee** [aandrew-me/ytDownloader#107]
Hello, some time we find playlist with many video for exemple documentarie, we want only dobwload the audio of some videos and play audio whan we sleep or send these audio files to our smartphone via snaddrop....

we wish to choose the worst audio quality of the youtube or facebook video for faster downloading and preserve the battery of our smartphone or little mp3player because I find the worst audio quality has a good level and we listen to it comfortably and economically hard drive size and battery power....so my suggestion is to add presets, i.e. download audio with just one click without choosing from list, we hope that clipboard of our beloved ytDownloader detect youtube or dailymotion and automatically star  downloads the worst audio quality with the preset "worstaudio" or download the worse video quality with the preset " http-380-1 " for the case of dailymotion because dailymotion does not have dash audio streams .... so it simplifies the process and makes it faster for poeple who wish to download youtube podcats or just download quickly and listen the audio of tv shows in youtube and dailymotion !

Thank you so much !

**Comment by aandrew-me** [comment]
So where do you want the 'worst audio' option to be?

**Comment by aandrew-me** [comment]
Ok. Since you want to download worst quality audio. If I add the option to the format list like this, will it be fine?
![image](https://user-images.githubusercontent.com/66430340/216780291-388e5de6-38fe-4842-b901-9006977e9dde.png)

**Comment by aandrew-me** [comment]
I can add a separate option with audio quality under **Extract Audio** and add an option to preferences to choose the default audio quality.

In case of video, you will already find an option in Preferences called, preferred video quality. Just select it to something low and it will automatically select a low quality in the list.

**Comment by trimechee** [comment]
@aandrew-me Wonderful marvellous ! We thank you very much and grateful to having invented and offered to the community this magnificent rare jewel of open-source technology, one of the very rare downloaders to offer a beautiful interface and exceptional options !!!

I don't understand videohelp what are they waiting for to add this wonderful program! maybe the program is recent and they are waiting for the number of users to increase, in any case I saw with pleasure that there are positive comments on alternativeto:
https://alternativeto.net/software/ytdownloader/about/

for softpedia, I did not find "submit program" section, just there is section "if you are a developer, you can send your software...", 

videohelp, they offer software of lower quality than our beloved ytDownloader, i will contact them again with a better description, ytDownloader is open source, ad free, popular on alternativeto and reddit....and has unique revolutionary options, i don't understand what they are waiting for to add this wonderful software ?!! why deprive the world of this marvelous software?!! I will contact videohelp again lol

**Comment by aandrew-me** [comment]
I really appreciate that! Thank you for your nice words.

The authors of softpedia added ytDownloader to their site.
https://linux.softpedia.com/get/Utilities/Youtube-Downloader-104274.shtml
https://www.softpedia.com/get/Internet/Download-Managers/YtDownloader.shtml

**Comment by trimechee** [comment]
Woahh I didn't know that ! awesome ! even so I searched but i didn't find ! surely I did not search well !


*offtopic :


Ahh just a remark, before, I was using "firedm" downloader formerly known as "pyidm", but this program has mysteriously disappeared, I don't really know, I'm not a developer, but since this program is open source , there is a person who managed to save it and don't really know if the developers can be inspired by the functionalities offered by firedm which unfortunately mysteriously dips from github, the firedm site puts a version which removes all the options so do not install the latest version but the penultimate version:

https://github.com/afzl-wtu/firedm

**Comment by aandrew-me** [comment]
Yeah looks like the original github repos got deleted.
https://www.reddit.com/r/Python/comments/u44t8y/firedm_repos_no_longer_exist/
But you can download for windows if you want from here
https://github.com/afzl-wtu/firedm/releases/tag/firedm

Or if you have Python you can install with pip
https://pypi.org/project/FireDM/

**Comment by trimechee** [comment]
Of course I'm not going to use firedm, I deleted it from my computer because it's no longer developed...just I remember it had a lot of options  and enhancements which I don't remember exactly and I think it's bad this legacy is disappearing and the developers should perhaps be inspired by it to find new ideas and improvements... but whatever, ytDownloader works wonderfully and it becomes one of my rare favorite programs :)
