### ISSUE TITLE
Exit or hybernate the program automatically after donwload complete

### ISSUE THREAD

**Issue by trimechee** [aandrew-me/ytDownloader#108]
Hello, somes times our Wi-Fi weak and therefore the download will take a long time, it will be great to add an option "close the program after download complete" because sometimes we forget to close the program when we use a lot of other programs and many web browser tabs and also add option "hybernate or shutdonwn computer after donwload finish", thank you very much !

**Comment by aandrew-me** [comment]
Ok I will add the option

**Comment by trimechee** [comment]
Great !!! Thank you very much :) 🥇

**Comment by aandrew-me** [comment]
Closing the program is possible. However due to restrictions in different Operating Systems, hybernate/shutdown is not possible:(
