### ISSUE TITLE
[Feature Request] allow manual format selection

### ISSUE THREAD

**Issue by soredake** [aandrew-me/ytDownloader#109]
**Description**
It would be nice if this can allow manually selecting audio/video formats like in Seal (android app)

Example from Seal:
![Screenshot_20230207-172316_Seal_compressed](https://user-images.githubusercontent.com/5204968/217289450-1f87d961-bbb0-42ca-ac18-5c0857ee7945.jpg)
![Screenshot_20230207-172330_Seal_compressed](https://user-images.githubusercontent.com/5204968/217289455-49e389ae-a95b-425b-8fc9-07364f09d207.jpg)

**Comment by aandrew-me** [comment]
I don't see the point here. The purpose of the app is to make it simple and it shows the available formats in a user friendly way. For more advanced stuff there is always the command line tool [yt-dlp](https://github.com/yt-dlp/yt-dlp)
