### ISSUE TITLE
 Download freeze or very slow download speed

### ISSUE THREAD

**Issue by trimechee** [aandrew-me/ytDownloader#115]
Hello, i tried the last version of "ytDownloader", ça met beaucoup de temps pour analyser les liens youtube et j'attends beaucoup puis le téléchargement des audio des vidéos démarre mais n'avance pas et freeze....

i tried with another  downloader which use also 'yt-dlp' and youtube download is very slow and limited 7kb/s and many people say yesterday  they encounter this kind of slow youtube download problem !

https://www.reddit.com/r/youtubedl/comments/11dzu0t/anyone_getting_throttled_on_ytdlp_20230217/

https://github.com/yt-dlp/yt-dlp/issues/6369

https://www.reddit.com/r/youtubedl/comments/11czulm/has_anyone_else_started_experiencing_some_youtube/

The other downloader has integrated graphical interface  for "lux" engine  dowloaderand i tried  lux and i can donwload very very fast from youtube without speed restriction....

I think it becomes a necessity to integrate new engines to "ytDownloader" like "lux" and " you-get " and N_m3u8DL because it seems that a censorship applies against yt-dlp and it seems downloading youtube video and audio becomes impossible in our beloeved "ytDownloader" :(

and we thank you very much for adding support for m3u8 files !! it's revolutionary !!

I think the size of the program doesn't matter and many users don't care about the size of the program even though the standard hard disk is 1 tetra Gb and we have several  usb keys  with tetra storage at very low prices.. ..personaly i think the most important thing for users is to be able to download videos or playlists quickly without bugs and freezes, no matter how big the program, even if it is many gigabits.....

 Thank you so much !

**Comment by aandrew-me** [comment]
Hello
I can see that download speeds have dropped.
"Integrating" a new engine basically means rewriting the whole program. That would take a lot of time, time which I don't have in my hands.

Now, yt-dlp being such a great tool should fix things. So we'll have to wait.
But if they don't fix and the issues persist, then I will move to a different engine.

**Comment by aandrew-me** [comment]
And yes, the video/audio files are downloaded with `-f`

**Comment by aandrew-me** [comment]
I have found a solution that you can use

create a config.txt file and put this line there
`--downloader aria2c`
Make sure you have aria2c installed and added to path.

Now if you download something, you should get good speed.
Let me know

**Comment by aandrew-me** [comment]
No problem!

This renderer.js file handles the downloads of videos/audios
https://github.com/aandrew-me/ytDownloader/blob/main/src/renderer.js

**Comment by trimechee** [comment]
Thanks :) i am trying to use aria2c even if i heard from users that aria2c doesn't work with this youtube bug throttling and personaly i tested yesterday "aria2c yt-dlp" with the other downloader and the speed still very low but i will try aria2c with ytDownloader :) shoudl i add "renderer.js" to config txt ?

**Comment by aandrew-me** [comment]
You don't have to add renderer.js to config.txt
Just add the line
`--downloader aria2c`

**Comment by aandrew-me** [comment]
> I should add the path of "aria2c.exe" to '--downloader aria2c' config.txt ?

oh you are on Windows. Is aria2c in PATH?

**Comment by aandrew-me** [comment]
I mean, when you open Powershell/Terminal/Command Prompt, are you able to execute `aria2c` command? 
For example `aria2c --version`

**Comment by trimechee** [comment]
I tried with command line and it says : "aria2c' is not recognized as an internal command
or external, an executable program or a batch file.", but now i download aria2c  may be shoud i add the executable of aria2ec.exe to the folder of config files of "ytDownloader" ?

**Comment by aandrew-me** [comment]
Download the aria2c zip folder from here
https://github.com/aria2/aria2/releases/download/release-1.36.0/aria2-1.36.0-win-64bit-build1.zip
Then extract the folder.
This folder contains `aria2c.exe` file.

Now you will have to add the folder to the environment variable called PATH
Check this article, you will get an idea on how to do it.
https://windowsreport.com/edit-windows-path-environment-variable/

Once you add the folder to the path variable, if you execute `aria2c --version`, you will not get the error anymore.

**Comment by trimechee** [comment]
Great ! I will try in sha Allah ! Thank you :)

**Comment by trimechee** [comment]
I was following the tutorial and it said that we had to click on "edit" and I click on edit and I was going to put the location of aria2c then fortunately at the last second I gave up because I was going to erase existing values, I have to find "C:\Windows\system32" and edit it and or just click on "new" button?

**Comment by aandrew-me** [comment]
You just have to click the new button and put the location of aria2c folder. You can also select that folder location by clicking on Browse

**Comment by trimechee** [comment]
I have tried many time changing the value, i clicked new in "system variable", variable name "aria2c", path "C:\aria2-1.36.0-win-64bit-build1\aria2-1.36.0-win- 64bit-build1" and tried again with "C:\aria2-1.36.0-win-64bit-build1\aria2-1.36.0-win-64bit-build1" and tried again with "C:\aria2- 1.36.0-win-64bit-build1\aria2-1.36.0-win-64bit-build1\aria2c.exe" then if I run cmd adminstrator and I get the same message "aria2c' is not recognized as an internal command
or external, an executable program or a batch file"...

anyway thank you for informing me about the environment variable, I find it very interesting and useful, I will try this feature to quickly open shortcuts like sound and disable wifi....


I noticed that "ytDownloader" does not display the download speed which can be useful to be able to compare and to know if the download is fast enough.... can "ytDownloader" display the download speed please ?

**Comment by trimechee** [comment]
AlhamdoulilAllah I finally managed to run aria2c! I did not understand that it was necessary first to find the box "path" in varaible system, then click on edit then on "new" then put C: then specify the path .... now the problem is that "ytDownloader" doesn't show the download speed so that I can compare, apparently I have to choose a file with a large size in order to compare....ahh or I'll choose a small video and see how long it takes" ytDownloader" can run it...

**Comment by aandrew-me** [comment]
Great that you could add.

Now add `--downloader aria2c` to a config.txt file and select the file from ytDownloader settings.

What do you mean by 'ytDownloader doesn't show download speed'?
![image](https://user-images.githubusercontent.com/66430340/222105376-aafb12b6-f9b6-4916-99be-88863e5f9478.png)

It only doesn't show speed when you select a specific time range.

**Comment by trimechee** [comment]
i tried and i have "an error has occurred, see details," I can see the details but I cannot copy them, there is no logs or diganostic button in "ytDownloader" so that we can send you the technical details please?

**Comment by aandrew-me** [comment]
Put your mouse on the error message, it should show something. Then take a screenshot

**Comment by trimechee** [comment]
yes i added "--downloader aria2c" to config txt but i get "an error has occured", ...i meant i didn't see the message "speed 400kib/s" when i tried without" aria2c", maybe I did not pay attention or the file size was so small that the download ended without me checking the mention of the download speed ....

**Comment by aandrew-me** [comment]
Ok, provide a screenshot and I will understand whats the problem

**Comment by trimechee** [comment]
I can't take a screenshot, the error pop up message disappears as soon as I click on the keyboard shortcut to take a screenshot, I can't take a screenshot, the error pop up message disappears as soon as I click on the keyboard shortcut to take a screenshot, but I'll try to tell you what this error message contains

**Comment by aandrew-me** [comment]
That's really a strange error. Looks like a connection issue

**Comment by aandrew-me** [comment]
If you are getting error, then don't use the config file. 

Instead open terminal and try this if you have yt-dlp installed
`yt-dlp --downloader aria2c https://www.youtube.com/watch?v=rUWxSEwctFU`

**Comment by trimechee** [comment]
Thank you so much  for yout help and sorry to have tired you with all my requests :) i have already "yt-dlp.exe" in C: to use it with mpc be media player....i have another downloader which combined yt-dlp and aria2c and even combined yt-dlp with ffmpeg and the download speed remains low or even non-existent 7kib/s, I think the yt-dlp team is finding a solution to this problem quickly because " lux" engine downloader does not suffer from this problem, I tried with getvideo site and the 3d youtube downloader program is downloading is very fast from youtube 500kb/s but I cannot download audio from facebook using getvideo and 3d youtube downloader....

**Comment by trimechee** [comment]
I should also add 'yt-dlp' to path enviroment viriable like aria2c ? beacause i have message yt-dlp is not recognized...

**Comment by aandrew-me** [comment]
> I should also add 'yt-dlp' to path enviroment viriable like aria2c ? beacause i have message yt-dlp is not recognized...

Forget it. I don't think it will help.

**Comment by aandrew-me** [comment]
> Thank you so much  for yout help and sorry to have tired you with all my requests :) i have already "yt-dlp.exe" in C: to use it with mpc be media player....i have another downloader which combined yt-dlp and aria2c and even combined yt-dlp with ffmpeg and the download speed remains low or even non-existent 7kib/s, I think the yt-dlp team is finding a solution to this problem quickly because " lux" engine downloader does not suffer from this problem, I tried with getvideo site and the 3d youtube downloader program is downloading is very fast from youtube 500kb/s but I cannot download audio from facebook using getvideo and 3d youtube downloader....

You can download from Facebook with ytDownloader. For YouTube, use something else for now

**Comment by aandrew-me** [comment]
Also there are many websites which you can try
For example
https://snapsave.app/

**Comment by aandrew-me** [comment]
Since this is a yt-dlp issue, I am closing the issue

**Comment by trimechee** [comment]
Awesome ! Thank you for sharing this site ! 💯 
 i often use getvideo.at beacause it has boomarklet and i can dowload youtube dailymotionfacevideo and audio with one clock and even watch video without ads !

so i put the bookmarklet of this site in my bookmarks bar and i trust this site, just i heard the bookmarkelet can contain javascript which can have malicious code and malware...please is this that you can take a look at the code of the bookmarklet of getvideo and see if there is something abnormal please?

https://getvideo.at/en/


javascript:(function(){ if (window.location.hostname == 'getvideo.at') { alert('Open a page containing a video and then click this button again'); } else { open('https:/ /getvideo.at/?url=%27%20+%20encodeURIComponent(window.location.href)%20+%20%27&utm_source=bookmarklet&utm_medium=redirect%27);%20%20%20%20%20%20% 20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20}%20%20%20%20%20%20%20 %20%20%20%20%20%20%20%20%20%20%20%20%20})();

**Comment by trimechee** [comment]
I undestand :) just one thing, it seemed to me that ytDownloader takes an unusual long time to parse and fetch the youtube links , not sure if its related to yt-dlp or youtube or other things... .even with 3D youtube downloader the analysis of the links takes a lot of time so it doesn't seem to be related to the downloaders apparently but to youtube perhaps, and perhaps in this case the downloaders can use tools to bypass this possible censorship, for example in 3D youtube downloader I see optin to use cloudflare dns...

**Comment by aandrew-me** [comment]
> 

The code you provided looks normal.
A website can't do much to your computer. The javascript in websites cannot access your computer files. All it can do is download something if you allow it to.

**Comment by trimechee** [comment]
Awesome !! Thank you so much for your precious help ! I had a doubt and I downloaded youtube video with 3D YOUTUBE DOWNLAODER and getvideo website and the download speed is very fast so the bug is really about yt-dlp , thanks for sharing the vpns :) me I have searched and I found a lot of vpn unlimited and free and often hidden...but I only use psiphon because it suits me, it is light and I don't need to hide my identity but to bypass geolocation... there is also opera browser vpn but it's not really a vpn but a proxy....

**Comment by trimechee** [comment]
Hello, i tried to download with dailymotion and the speed is very good and two to three times faster than other downloader which uses yt-dlp, thank you very much! I see the speed 80kb/s then increase to 200kb/s then drop to 80kb/s then become 200kb/s again, it's very good and fast, bravo!
in the other downloader the speed remained at a constant speed of 40kb/s or 80kb/s....

**Comment by trimechee** [comment]
and i tried wih vpn and the speed is again very fast....but the vpn should apply to all apps of the os like for dowloader...
