### ISSUE TITLE
Remember video/audio Window and Add Batch download support

### ISSUE THREAD

**Issue by trimechee** [aandrew-me/ytDownloader#116]
when I copy paste a youtube link and I just want to download the audio, it's the "video" window with the video settings that appears by default, it will be great if we can change this default display in the settings so that I see first the "audio" window and the audio parameters and not the video parameters or that ytDownloader remembers my last choice i.e. I clicked on the audio button in order to check the size of the audio file, yes I know there is fixed "extract audio" button but I have to click on "audio" in order to check the quality and size of the audio download....or that the "extract audio" button also shows us the infirmation on the audio file by example its size before we download it...

also i see that ytDownloader offers a choice of audio format "m4a, opus...", i think it will be great to add an option for ytDownloader to automatically choose the best possible audio format without conversion for audio quality "worst audio" in order to save battery and time and avoid unnecessary conversions from one audio format to another, because for example you can choose the "opus" format with ignorance and therefore ytDownloader will convert the original m4a audio file to opus for example and it will take a long time, or maybe we choose m4a and the original audio file does not have m4a format and so ytDownloader will download large original audio file then convert it to m4a which is slow, I mean we doesn't care about the audio format because windows and android music players can play a lot of audio formats, I think what matters for users is that ytDownloader chooses us the original audio format without conversion regardless of whether it is m4a, opus, ogg....because for example I don't know what is the original youtube audio format of "worst audio" preset, m4a or opus or ogg.....and on other sites we do not know the format of the original audio by default hence my request that ytDownloader automatically choose the original audio stream by default regardless of its format, i.e. it is not the user who should choose the format but ytDownloader to avoid converting from one format to another! Thanks a lot !

when I find a video playlist of a radio channel on youtube or youtube tv show, I want to download only a few shows, it will be great if ytDownloader add "batch donwloader" option and the video that we select from the playlist and we copy them address are automatically added to ytDownloader because sometimes the tv show has several extracts and I have to copy and paste the addresses then click on ytDownloader and click on the "paste from clipboard" button and it's tiring when you're going to copy 20 addresses of video, it will be great to add a option "watch clipboard" and ytDownloader will automatically add all links that are in the clipboard even unsupported links and even non-video links then ytDownloader will just show an error message if this or that link in the clipboard is not supported and cannot be downloaded because sometimes you can mix video links with other links or text selections!
ou our beloved ytDownloader adds monitoring of clipboard links and automatically adding them to a queue only if the links come from youtube and dailymotion because these are the most famous and popular sites in the world and ytDownloader ingests other links and does not not add them to a queue except when manually clicking "paste from clipboard"!
I know I'm asking a lot and I apologize and  i thank you immensely ! 💯 🥇

**Comment by aandrew-me** [comment]
I would request you to create one issue for one feature only.

Now regarding your requests.

1. Its possible. I will add code so that ytDownloader remembers which Window was used and will switch to it.
2. Audio formats provided by ytDownloader are the ones directly provided by Youtube. There is no conversion there.
3. When I will get time, I will add batch download feature

**Comment by trimechee** [comment]
Great ! Thank you :) and sorry, the ideas have accumulated while writing my message lol, should I rewrite my resquest and divide them in 3 issues?

**Comment by aandrew-me** [comment]
No need, I understood you

**Comment by aandrew-me** [comment]
> Thank you :) just to clarify why I asked that because I saw your precious answer "Audio formats provided by ytDownloader are the ones directly provided by Youtube. There is no conversion there.", I mistakenly thought there is conversion because in the dropdown from the "extarct audio" button, I saw the "mp3" format, youtube contains native mp3 format dash audio?

The audios in Audio Window are provided by Youtube (m4a and opus)
Other ones are somehow converted by yt-dlp. I don't know how.

**Comment by trimechee** [comment]
Very Interesting , thank you !

**Comment by trimechee** [comment]
Great ! Thank you :) 👍
