### ISSUE TITLE
[Feature Request] use actual playlist numbers when downloading playlist range

### ISSUE THREAD

**Issue by soredake** [aandrew-me/ytDownloader#118]
**Description**
When i tried to download playlist range 5-12 i've seen this and thought that ytdownload is ignoring playlist range that i set and downloading playlist from the start:
![Снимок экрана 2023-03-07 124612](https://user-images.githubusercontent.com/5204968/223400754-7073a199-2b73-45e9-a697-4cfd2d4ea5dc.png)

It will be nice if ytdownloader can show actual playlist item number like "video 5, video 6 etc"

**Comment by soredake** [comment]
Also ytdownloader can't show cyrillic in playlist name.

**Comment by aandrew-me** [comment]
Hello
Can you please provide the link to the playlist, it will make it easier for me

**Comment by soredake** [comment]
@aandrew-me of course https://www.youtube.com/playlist?list=PLNu0CXJQy5DBk_ca7C7YOZUFC8XzIYuQf

**Comment by aandrew-me** [comment]
![image](https://user-images.githubusercontent.com/66430340/223408070-5d24df9a-c2ea-4dda-a091-1eba1c481dc3.png)
Strange its working fine for me, sounds like the operating system is not supporting the characters.

What Operating System are you using?

**Comment by aandrew-me** [comment]
Also you can choose Russian language for the app from Preferences if you want.

**Comment by aandrew-me** [comment]
Now regarding the number, I will try to make the correct number visible.
Also after its downloaded, the correct number is there in the file's name on your computer

**Comment by aandrew-me** [comment]
✅ Actual playlist numbers will be shown from the next update.

**Comment by soredake** [comment]
> What Operating System are you using?

Windows 11

> Strange its working fine for me, sounds like the operating system is not supporting the characters.

All other programs display russian fine.

>Also you can choose Russian language for the app from Preferences if you want.

I know, i change usually use english for screenshots when i create issues.

**Comment by aandrew-me** [comment]
Hm okay that's strange. I will see what I can do
