### ISSUE TITLE
[BUG] wrong quality is downloaded when downloading playlist

### ISSUE THREAD

**Issue by soredake** [aandrew-me/ytDownloader#120]
**Bug Description**
I tried to download videos from this playlist https://www.youtube.com/playlist?list=PLNu0CXJQy5DBk_ca7C7YOZUFC8XzIYuQf
I selected `1080p` quality but videos are downloaded in `720p` instead.

**To Reproduce**
1. Try to download videos from this playlist in 1080p for example.
2. They will download in 720p.

**Screenshots**

**Info (please complete the following information):**
 - Operating system: Windows 11 Pro.
 - App version: 3.12.0
 - Package version (flatpak/snap/other):

**Comment by aandrew-me** [comment]
Thanks for reporting this.

I realized that it happens when the quality is 1080p60. I will fix it

**Comment by aandrew-me** [comment]
Should be fine from next update
