### ISSUE TITLE
[Feature Request] option to touch files (update the download date) after downloading

### ISSUE THREAD

**Issue by Sevenseraphim** [aandrew-me/ytDownloader#123]
Hey, just want to say that this is the best youtube downloader program i've used by far, it downloads videos very quickly and is very lightweight and easy to use... 

I just have one small request, when I download any video from youtube it saves the file with the original creation/modification date... This is an issue for me because I sort files in folders by descending modification date and the video always gets lost among the many downloads I have in my downloads folder and I have to manually use terminal to "touch" each file individually to update the date. 

I would really appreciate it if you could have the option to update the modification date of the video (by using the touch command or any other means) to the current date after downloading and also if possible to have the option to rename a file before downloading...

Thank you so much for your hard work and for such a great program... Cheers! 😊

**Comment by aandrew-me** [comment]
Hello!

Thanks for your nice words.
Now, you mentioned 2 things.

1. I have already added code so that videos/audios that have been downloaded will have the modification date of when they have been downloaded. So it will be available in next update.

2. Option to rename the file would be great. I will try to implement it.

Have a nice day/night!

**Comment by Sevenseraphim** [comment]
Wow that was a quick reply, thank you so much! hope you have an absolutely aweSome day... 😁

**Comment by aandrew-me** [comment]
Ok expect to see both in the next update.

**Comment by aandrew-me** [comment]
Update is available. Let me know if everything is working as expected

**Comment by Sevenseraphim** [comment]
You sir are an absolute champ. I literally commented for the first time just 6 hours ago and you solved both issues and cleanly implemented them... hats off to you! 🤠

I tested changing the filename before downloading, I even tried adding "?" and ".mp3" at the end of the filename to see if it would mess up or fail but it works perfectly and adds the correct file extension afterwards (.mp4 in my case) and the file modification date is now correct and automatically goes to the top of my folder. THANK YOU SO MUCH!  🎉🥳🎉 

I've been using this program for several months now and these two issues have always bothered me but I never posted about them before. Seriously thank you so much, your program is now flawless as far as i'm concerned. 10/10 👍🏻😁👍🏻

May you live long and Arch Linux... 🖖🏻

**Comment by aandrew-me** [comment]
Hey!
Thanks for the nice words.

Yes all you have to do is change the title and the app will take care of the extension.

Cheers!
