### ISSUE TITLE
[Feature Request] Publish to microsoft store in msix format

### ISSUE THREAD

**Issue by soredake** [aandrew-me/ytDownloader#124]
**Description**
Example benefits of msix package format:  https://github.com/felixrieseberg/windows95/issues/221 https://learn.microsoft.com/en-us/windows/msix/overview#key-features

**Comment by aandrew-me** [comment]
Publishing to Microsoft store is not free.

**Comment by soredake** [comment]
@aandrew-me if i understand correctly it's only 20$ https://www.advancedinstaller.com/msix-publish-microsoft-store.html

I can donate this later.
