### ISSUE TITLE
New cli engine for DASH-MPEG or DASH-WebM MPD manifest dash-mpd-cli

### ISSUE THREAD

**Issue by trimechee** [aandrew-me/ytDownloader#125]
Hello, I discover this new amazing cli downloader engine which has the rare feature of downloading videos that other tools cannot download because it can download media content from a DASH-MPEG or DASH-WebM MPD manifest !
 It will be great to integrate this software to our beloved ytDownloader, thank you so much !

https://github.com/emarsden/dash-mpd-cli

"This application is able to download content from certain streams that do not work with other applications (for example xHE-AAC streams which are currently unsupported by ffmpeg, streamlink, VLC, gstreamer)."

DASH features supported
VOD (static) stream manifests
Multi-period content
XLink elements (only with actuate=onLoad semantics), including resolve-to-zero
All forms of segment index info: SegmentBase@indexRange, SegmentTimeline, SegmentTemplate@duration, SegmentTemplate@index, SegmentList
Media containers of types supported by mkvmerge, ffmpeg or VLC (this includes ISO-BMFF / CMAF / MP4, WebM, MPEG-2 TS)
Subtitles: preliminary download support for WebVTT, TTML and SMIL streams, as well as some support for the wvtt format.

**Comment by aandrew-me** [comment]
This is a download tool. My app uses yt-dlp. So its either yt-dlp or this....

**Comment by trimechee** [comment]
I prefer you tool because i don't know how use such cli tools...
