### ISSUE TITLE
the path problem not fix yet

### ISSUE THREAD

**Issue by spidy2356** [aandrew-me/ytDownloader#13]
![Uploading IMG_20220903_191351.jpg…]()

**Comment by aandrew-me** [comment]
Are you using the latest version? And you tried to upload a picture but it didn't get uploaded.

**Comment by spidy2356** [comment]
yes I use the latest version 3.1.1. and here the picture
![IMG_20220903_191351](https://user-images.githubusercontent.com/101243689/188282812-10b9b3dc-379a-497d-8e02-cc85cf9dabe8.jpg)

**Comment by aandrew-me** [comment]
Thanks you very much!

I understood the problem. I am fixing it.

**Comment by aandrew-me** [comment]
I will publish an update soon. Please let me know after trying it.
