### ISSUE TITLE
[Feature Request] Ability to download the metadata of downloaded music from Youtube Music

### ISSUE THREAD

**Issue by Terkyz** [aandrew-me/ytDownloader#133]
**Description**
First of all, I don't know if this is possible, but if it is I would like to be able to download music in the style of [AllToMP4](https://alltomp3.org/) where my music downloads its metadata automatically and allows me to organize my music library more comfortably without having to edit each thing manually.

Maybe the description is a little clear, I don't want to have a button to "Download the metadata of this already downloaded file" but a button to "Download file with metadata".

**Comment by aandrew-me** [comment]
Hmm looks like the tool AllToMP3 gets the Music metadata from [AcoustID](https://acoustid.org/) and then embeds it into the file. I will try to do it.

However there are already a tool you can use -
https://ytmdl.deepjyoti30.dev/

**Comment by aandrew-me** [comment]
Okay so all those Metadata is not provided by Youtube and the only way to get those is by using the API of a service like Spotify. And this is beyond the scope of this app. There are apps and tools dedicated to downloading and listening to Music, so its best to use them.

Here are some programs that can help you with that
- [Muffon](https://muffon.netlify.app/)
- [youtube-music](https://th-ch.github.io/youtube-music/)
- [Ytmdl](https://ytmdl.deepjyoti30.dev/)

For Android there are 
- [Musify](https://gokadzev.github.io/Musify/)
- [Blackhole](https://github.com/Sangwan5688/BlackHole)
