### ISSUE TITLE
Remove old updates 

### ISSUE THREAD

**Issue by trimechee** [aandrew-me/ytDownloader#134]
Hello, I noticed when there is an update made via the ytDownloader updater, ytDownloader does not erase old downloaded versions, and over time it can take up a lot of space...

**Comment by aandrew-me** [comment]
Okay thanks for reporting this. I will analyze it

**Comment by trimechee** [comment]
Great , thank you !

**Comment by aandrew-me** [comment]
Looks like the library doesn't handle this properly. So I would need to manually delete old updates. For that I need to know exactly where they are and how they look like. So I would need more details from you

**Comment by trimechee** [comment]
Great ! I will try to find these folders in sha Allah !

**Comment by trimechee** [comment]
Hello @aandrew-me , thank you for investigating ! 

I have just done a fresh installation, I think the updates are in this folder, what is surprising is I uninstalled then reinstalled Ytdownloader and normally the ytdownloader-updater folder should be empty because the fresh installation....

C:\Users\Asus\AppData\Local\ytdownloader-updater

**Comment by aandrew-me** [comment]
This updater file is required

**Comment by trimechee** [comment]
And the old updater file ?

**Comment by aandrew-me** [comment]
I have added code to remove everything in that updater folder. It will be in next release. I will have to test that things don't break if everything is deleted

**Comment by trimechee** [comment]
Awesome !! Thank you so much Mr @aandrew-me :) 💯 🥇

**Comment by aandrew-me** [comment]
Create a new issue again if there are some issues
