### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by bambukouk** [aandrew-me/ytDownloader#135]
**Bug Description**
I have downloaded YTdownloader on yet another PC (satisfied user - thank you)
but... this time flathub also installed `YT music`
I didn't want it, I didn't ask for it, do I need it to run YTdownloader?
**To Reproduce**
1. 
install using flathub
**Screenshots**

**Info (please complete the following information):**
 - Operating system: 
           Distro: MX-21.3_KDE_x64 Wildflower January 15  2023 
           base: Debian GNU/Linux 11 (bullseye) 
 - App version:
      app.ytmdesktop.ytmdesktop/x86_64/stable io.github.aandrew_me.ytdn/x86_64/stable

 - Package version (flatpak/snap/other):
           flatpak

For now I have unistalled it :-1:

**Comment by aandrew-me** [comment]
`YT Music` has nothing to do with ytDownloader. I don't know how it got installed. And I searched on flathub and couldn't even find a program called `YT Music`.

So..???..!!??

**Comment by bambukouk** [comment]
Well... I am just as puzzled
I will try again, this time extra slowly and checking all the steps to see if something was caused by my stupidity

Ps thank you for such a quick response :1st_place_medal:

**Comment by bambukouk** [comment]
well...
did exactly the same, using the following command:
`flatpak install flathub io.github.aandrew_me.ytdn`
and this time it took 1/10 of time and just installed YTdownloader.

Either me, or some mystery...
regardless - **solved**
(and sorry for my initial overreaction)

**Comment by aandrew-me** [comment]
Haha, well then, have a nice day/night!
