### ISSUE TITLE
Impossible to download from uqload

### ISSUE THREAD

**Issue by trimechee** [aandrew-me/ytDownloader#139]
Hello, I am trying to download the video from the Uqload player of this site

https://vostfree.ws/845-hello-world-vostfr-movie-ddl-streaming-1fichier-uptobox.html

using the stream-detector extension:

https://github.com/54ac/stream-detector

by activating the option "copy stream url as yt-dlp" command" of the addon "stream-detector" then I play the video Uqload and copy paste the url obtained from stream detector in 
ytDownloader but ytDownloader does not succeed to download the video from Uqload, streaming sites seem to have strengthened their mechanism to prevent downloading videos easily, I hope that 
ytDownloader will add an option to receive commands from the "stream detector" extension and so we can download the video, I even tried to activate the use of command of external dowloader for yt-dlp" option of the "stream-detector" extension but it doesn't work no....i also hope that we can preview and watch the part downloaded by ytDownloader  with a video player without waiting for the download of the video to finish so it will be great that ytDownloader  does not download much sections at the same time to speed up the download but just a segment so that we can watch the video before the end of the download, thank you very much !

i verify and Uqload platform is supported by yt-dlp so ytDownloader is supposed to be able to download from Uqload.....

https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md

**Comment by aandrew-me** [comment]
I tested downloading it with `yt-dlp` and it said `ERROR: Unsupported URL`. So its a `yt-dlp` issue. So you should open an issue on their page.

**Comment by aandrew-me** [comment]
And if you want to watch the video when its being downloaded, just open it with a video player like VLC and watch

**Comment by trimechee** [comment]
![image](https://github.com/aandrew-me/ytDownloader/assets/76402212/7aae2a93-eb8f-4683-bd08-6bcf5a26008b)

**Comment by trimechee** [comment]
Oups, sorry, i didn't see your first message lol....yeah i think it is certainly yt-dlp bug....

**Comment by trimechee** [comment]
and if the downloaded video is split in many parts and the downloader use multi trhread...i can't watch video while it is downloading...but i don't know if yt-dlp use multithread download to speed up download...
