### ISSUE TITLE
Auto select the best quality when downloading mp3s

### ISSUE THREAD

**Issue by lil5** [aandrew-me/ytDownloader#140]
**Bug Description**
Auto select the best quality when downloading mp3s

**To Reproduce**
1. Select yt video
2. Try to download the best quality mp3
3. Do it again with another yt video

**Info (please complete the following information):**
 - Operating system: Fedora
 - App version: 3.14.0
 - Package version: flatpak

**Comment by aandrew-me** [comment]
What's the bug here? I don't understand

**Comment by aandrew-me** [comment]
Firstly, you reported this as a bug, but as its evident, you are asking for a change in behavior instead.

Secondly, by default the quality for `mp3` is `normal`, not `worst`.
And when you download multiple mp3s, your previous choice is remembered here.

Now regarding to your request, 
Making `highest` as the default is not the best idea.
