### ISSUE TITLE
[Feature Request] Subtitles for playlist

### ISSUE THREAD

**Issue by TechMorgan** [aandrew-me/ytDownloader#141]
**Description**
Include an option to download subtitles when downloading playlist
And another option to select only available video formats of the playlist

**Comment by aandrew-me** [comment]
Option to download subtitles can be added. A playlist doesn't have 'available video formats'. Available video formats are different for each video, so its impossible to add

**Comment by TechMorgan** [comment]
> A playlist doesn't have 'available video formats'. Available video formats are different for each video, so its impossible to add

Can't it be added like this?
https://images.prismic.io/snapdownloader/7f50d3e4-58b8-471e-bc93-208e2c0674c3_how-to-download-youtube-playlists-3.png?auto=compress,format

**Comment by aandrew-me** [comment]
Possible but it will take time

**Comment by ZennMystic** [comment]
I switch from another app that even though it does download subtitles I prefer to your app keep up the good work.

Once subtitles and cover art (I'd really like that, is added I'll have everything I need. Great app TY
