### ISSUE TITLE
Add support of ytdl-patched 

### ISSUE THREAD

**Issue by trimechee** [aandrew-me/ytDownloader#142]
Hello, ytdl-patched has many enhancements and features and bug fixes in comparaison to yt-dlp, it will be amazing to add support for this wonderful software, thank you very much :)

https://github.com/ytdl-patched/ytdl-patched#new-features-in-ytdl-patched

**Comment by aandrew-me** [comment]
What I can do is let create an option that lets users use different yt-dlp. 

At this moment if you want, you can replace the existing yt-dlp binary with this one.

Go to `%HOMEPATH%\.ytDownloader` and you will see `ytdlp.exe`. Just replace it with your desired yt-dlp, but make sure its named `ytdlp.exe`

**Comment by aandrew-me** [comment]
I am gonna pass this one because its only for a very specific use case and such users can just replace on their own
