### ISSUE TITLE
Make ytDownloader compatible with the stream-detector extension commands

### ISSUE THREAD

**Issue by trimechee** [aandrew-me/ytDownloader#143]
Hello, I am trying to download the video from the Uqload player of this site

https://vostfree.ws/845-hello-world-vostfr-movie-ddl-streaming-1fichier-uptobox.html

using the stream-detector extension:

https://github.com/54ac/stream-detector

by activating the option "copy stream url as yt-dlp" command" of the addon "stream-detector" then I play the video Uqload and copy paste the url obtained from stream detector in ytDownloader but ytDownloader does not succeed to download the video from Uqload, streaming sites seem to have strengthened their mechanism to prevent downloading videos easily, I hope that ytDownloader will add an option to receive commands from the "stream detector" extension and so we can download the video, I even tried to activating the "use external dowloader for yt-dlp" option of the "stream-detector" extension but it doesn't work no....i also hope that we can preview and watch the part downloaded by ytDownloader with a video player without waiting for the download of the video to finish so it will be great that media-donwloader does not download many sections at the same time to speed up the download but just a segment so that we can watch the video before the end of the download, thank you very much !

i verify and Uqload platform is supported by yt-dlp so media-downloader is spposed to be able to download from Uqload.....

https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md

i find also another video extension open source and it will be great to make it compatible with the download manger, thank you :)  

https://github.com/chandler-stimson/live-stream-downloader

**Comment by aandrew-me** [comment]
Can you send the copied URL and the yt-dlp command ? I am unable to copy for some reason

![ksnip_20230709-145053](https://github.com/aandrew-me/ytDownloader/assets/66430340/922bac6c-227c-4aca-91b8-695a51672772)

**Comment by aandrew-me** [comment]
I tried the yt-dlp command but it doesn't download anything
```
 yt-dlp --no-part --restrict-filenames -N 4 --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36" --referer "https://uqload.co/" "https://m130.uqload.co/3rfkwsc3brw2q4drdih7dn5zlfxi4mazrlp777bedpqaofpk7uxjcerbemxq/v.mp4"
[generic] Extracting URL: https://m130.uqload.co/3rfkwsc3brw2q4drdih7dn5zlfxi4mazrlp777bedpqaofpk7uxjcerbemxq/v.mp4
[generic] v: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
WARNING: [generic] URL could be a direct video link, returning it as such.
[info] v: Downloading 1 format(s): 0
[download] Resuming download at byte 14
[download] Unable to resume
[download] Destination: v-[v].mp4
[download] 100% of     14.00B in 00:00:00 at 34.45B/s
```

**Comment by aandrew-me** [comment]
Well you are extracting the command from the browser. If it doesn't work with `yt-dlp`, it won't work with `ytDownloader`

**Comment by 54ac** [comment]
I'm not familiar with this tool or uqload, but you don't really need any GUIs with Stream Detector, you just paste the command in the terminal and it downloads the video. Nowadays yt-dlp supports extracting cookies from the browser, e.g. ```--cookies-from-browser firefox```, maybe it'd work if you added that to the command.

**Comment by aandrew-me** [comment]
If it works with `yt-dlp` it will work with `ytDownloader` and you can use cookies in `ytDownloader` too, so I am closing this
