### ISSUE TITLE
[BUG] How do I uninstall?

### ISSUE THREAD

**Issue by ehulsizer** [aandrew-me/ytDownloader#144]
**Bug Description**
There is no documented process, code base, computer program, or otherwise instructed construct inw hich to de-install such.

**To Reproduce**
1.  Look on GitHub
2. See if there's a thing to dis-install
3. Realize there is not

**Screenshots**

**Info (please complete the following information):**
 - Operating system: Macintosh
 - App version: Latest 
 - Package version (flatpak/snap/other): other

**Comment by aandrew-me** [comment]
Process of Uninstalling programs is elementary knowledge. It doesn't get any easier in MacOs. In Finder go to Applications, find YTDownloader, right click and move to Bin/Trash

**Comment by ehulsizer** [comment]
I know how to remove Applications on a Mac. It's not in the Applications Folder. I addition, the installation scripts installed a bunch of other dependencies into /usr/bin and other system folders. WHere's the script to remove all those?
