### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ehulsizer** [aandrew-me/ytDownloader#145]
I know how to remove Applications on a Mac. It's not in the Applications Folder. I addition, the installation scripts installed a bunch of other dependencies into /usr/bin and other system folders. WHere's the script to remove all those?

**Comment by ehulsizer** [comment]
This set of commands installs a bunch of stuff, including Electron:

git clone https://github.com/aandrew-me/ytDownloader.git
cd ytDownloader
npm i

Where's the npm command to remove al the cruft?

**Comment by aandrew-me** [comment]
Thats not the way to install the app. Its the way to run and build the app

**Comment by aandrew-me** [comment]
Those commands are for developers, aka for people who know what they are doing.
And removing the folder will remove everything installed.

**Comment by ehulsizer** [comment]
You don't know anything about me you idiot. Don't lash out just because you produce a shitty open source product that you don't maintain. I've been a developer and working with computers since you were still in diapers.

Do us all a favor and close your GH account, pack it in buddy and become a ditch digger.

**Comment by aandrew-me** [comment]
That behavior is certainly childish and disrespectful. Its an open source project, I don't owe you anything, if you don't like it, no one is forcing you to use it. Also the fact that you were a developer makes it even worse for you
