### ISSUE TITLE
[BUG] Please wait,necessary files are being downloaded

### ISSUE THREAD

**Issue by lion-no-back** [aandrew-me/ytDownloader#149]
![ytdownload](https://github.com/aandrew-me/ytDownloader/assets/100990301/2b35da1c-c5b0-40e9-a50b-243209fbe3ed)

Question: Downloads always fail
Environment: Windows11
Version: YTDownloader 3.14.2

**Comment by aandrew-me** [comment]
Interesting. Can you tell me your username on Windows?

**Comment by lion-no-back** [comment]
My username on Windows is shs.

**Comment by aandrew-me** [comment]
Could it be related to internet connection?

One way you can solve this is by manually downloading yt-dlp from this link
https://github.com/yt-dlp/yt-dlp/releases/download/2023.07.06/yt-dlp.exe

Then go to `C:\Users\shs\`
You can go there by pressing `Win + R` and typing `%USERPROFILE%`
Once you go there, create a folder called `.ytDownloader` and put that exe there and rename it to `ytdlp.exe`

**Comment by lion-no-back** [comment]
I moved ytdlp.exe to the installation directory and sovled this question.
![image](https://github.com/aandrew-me/ytDownloader/assets/100990301/7e382ab4-1cb5-43f7-85e6-715c7b948c85)
But I think it's unfriendly that there is no progress bar when downloading.
![process](https://github.com/aandrew-me/ytDownloader/assets/100990301/30d609df-db1f-4aa8-b774-54f1a0c8cd53)
Thank you for your active answer.

**Comment by aandrew-me** [comment]
Don't you see playlist downloads like this
![image](https://github.com/aandrew-me/ytDownloader/assets/66430340/d9471b46-3b9c-4156-bac6-3470af2549d8)

**Comment by aandrew-me** [comment]
Don't you see playlist downloads like this?

![image](https://github.com/aandrew-me/ytDownloader/assets/66430340/e192e8b8-0b0a-4d33-99e1-df81b839e8b8)
