### ISSUE TITLE
Exe executable version for windows 64bits

### ISSUE THREAD

**Issue by trimechee** [aandrew-me/ytDownloader#151]
Hello, thank you for the new version ! I notice there is no more exe version for windows 64bits in relaeses page ?

**Comment by aandrew-me** [comment]
Hello,
![image](https://github.com/aandrew-me/ytDownloader/assets/66430340/aebf20d4-20df-4dae-a4bb-1ca8b4f366bb)

There are 3 versions, zip, exe, msis

**Comment by trimechee** [comment]
It's very strange ! i make screenshot, i verifiy, there is no exe version ! 
![image](https://github.com/aandrew-me/ytDownloader/assets/76402212/db69e300-2103-4a2d-a801-cee6cbb64f22)

**Comment by aandrew-me** [comment]
In your screenshot there is an option - Show all 16 assets, you will find there

**Comment by trimechee** [comment]
Ohh that's true ! Sorry and thank you for your precious help @aandrew-me  :) 

i have problem please : since I didn't know where to find the exe version, yesterday I disabled the option that prevented having automatic update and now I open our so beloved YtDownloader and i verify in settings and i see version 3.14.1 so i don"t use the last version even despite automatic updates are enabled, I even left YtDownloader open for a long time so that the update finished and I restarted but still I see version 3.14.1

**Comment by aandrew-me** [comment]
If you are facing such problems, its best to download manually and install (update) it

**Comment by trimechee** [comment]
That's what i did :) 👍
