### ISSUE TITLE
Set default "m4a" format when we click on the "Extract Audio" option

### ISSUE THREAD

**Issue by trimechee** [aandrew-me/ytDownloader#152]
I would like to recommend the magnificent exceptional ytdownloader to my friends and family .... and you have been generous to have added the magnificent option that allows you to download only audio flows!

And since my friends or family may not know very much in storm, when they will click on the extract audio option, the default downloaded format will be the "mp3" format they will have to wait a lot so that there is conversion From M4A format to MP3 extension especially if the downloaded audio file is very bulky and I tested it myself, convert M4A file to MP3 file takes a long time!

So my request to facilitate things to beginners is that Our Beloved ytdownloader Drinks by default the "M4A" format or the "opus" format easy and quick to download and without the need for conversion when you act the option "extract audio", thank you a lot !

**Comment by aandrew-me** [comment]
Everything in 'Extract audio' is extracted, even m4a. That's why there is separate audio tab. And mp3 is more known and supported and people who need can change it in settings anyways.

**Comment by trimechee** [comment]
Interesing to discover, thank you :) 👍
