### ISSUE TITLE
Dash audio and mp3 conversion fail 

### ISSUE THREAD

**Issue by trimechee** [aandrew-me/ytDownloader#153]
Hello, sometimes I have to download several videos from a youtube channels and to make the download even faster, I choose the worst audio quality, I tried to download the worst audio quality of this video and then convert it to mp3 because I put tv and radio programs in a usb key connected to a radio that only plays MP3 audio formats .... and I noticed that the download took a very big long time despite I clicked on the extract audio option and I chose the worst audio quality....so I deduce that probably YtDownloader did not choose to download the worst audio quality dash but it downloaded a video and not the audio, in addition I haveve waited for a long time for converting to format mp3 and after this a long wait, YtDownloader gives me an audio file with "m4a" format and not with "mp3" format and I need the MP3 format to put it in a radio which has a usb hub and which only reads mp3 audio files....so my request please  is to download the audio dash format when we click on the "extract audio" option and when we chooses the worst quality, and also solve this bug where YtDownloader fails to convert the downloaded audio file to mp3, thank you very much !

https://www.youtube.com/watch?v=CKoB7ocMG58

**Comment by aandrew-me** [comment]
Let me clarify,
When you extract audio, `yt-dlp` downloads webm video and converts it to audio. If you want to download audio, download it from the Audio tab instead.

I tried extracting the mp3 from the link provided, it took some time to process it but it did provide mp3 file. I tested it on both Windows and Linux, so I can confirm that there is no bug here.

**Comment by trimechee** [comment]
Have you tried the option "MP3 audio format" from the option "extract audio"? i have file with m4a extension when i download audio with MP3 format with choosing option "extract video"....

i use yt-dlp with another gui downloader and i put thise preset "-f worstaudio -x" because the old preset "worstaudio" doesn't work any more efficiently with yt-dlp, and i monitor the download very fast the dash audio of youtube video and downloaded file has extension "m4a" without conversion , so I find it surprising that to download dash audio with YtDownloader , it took me 4 or 5 minutes to download the file with a speed of 400 kb/s and 5 minutes or more for the conversion....i will try to do other tests by choosing the m4a format with the worst quality...

**Comment by trimechee** [comment]
I read again and i undersand now, tahnk you, if extract audio leads to downloads webm video and converts it to audio, it may loose  the interest and benefits of this special option because in my opinion, the interest of extract audio is to download the dash audio quickly and save the data plan without needing to download the video .... we hope the extract audio option will have a "dash audio" option streams only" to download only audio streams dash without the need of donwloading video webm, thank you :)
