### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by BestDeirdre** [aandrew-me/ytDownloader#157]
Failed to download necessary files.Please check your network and try
again

**Comment by BestDeirdre** [comment]
![image](https://github.com/aandrew-me/ytDownloader/assets/61332793/7a08908c-30c7-41ba-822f-81aac6b7e29c)

**Comment by aandrew-me** [comment]
This should work fine if the app has permissions to write to config directory and access internet. So its most likely an issue on your end. You need to provide more details
