### ISSUE TITLE
[BUG] Minor usability enhancements

### ISSUE THREAD

**Issue by evering88** [aandrew-me/ytDownloader#159]
**Bug Description**
-Lack of DE icons. (tested in Plasma 5). The only way to launch it is using in a console "flatpak run io.github.aandrew_me.ytdn"
-Ignores the configured XDG directories. There are hardcoded by default. E.g. my download directory is $HOME/Descargas by default the downloads go to $HOME/Downloads
-The list of qualitys to do the download is confusing. Less options are best to enhance the usability

**To Reproduce**
1. Only installing it

**Info (please complete the following information):**
 - Operating system: ArchLinux updated 64 bits
 - App version: 3.14.2
 - Package version (flatpak/snap/other): Flatpak

Thanks for your app! Regards

**Comment by aandrew-me** [comment]
That is really strange
1. I am on Plasma 5 arch and the flatpak  version has desktop icon
2. Download directory can be chosen in app Preferences
3. That's a valid point, but some people want more info, some want less. I can add an option in settings to show more info

**Comment by evering88** [comment]
1. I've tested in my work PC and the icon works, appearing in "Utilities" submenu. Dimiss this

2. The option to change it exists, there is no problem with lacking options in this case. But the correct option is using by default the response of the "xdg-user-dir DOWNLOAD" command

3. less is more for the most of the users. May be keeping the full options in a "more..." or "advanced" option

Thanks for your awesome job! Regards
