### ISSUE TITLE
Add easy quick option to  Support  aria2c or wget to bypass youtube throttling

### ISSUE THREAD

**Issue by trimechee** [aandrew-me/ytDownloader#166]
Hello, even with the new version of yt-dlp, youtube throttle the flow on external applications and the download speed is set at 90kb/s in youtube, I think it becomes urgent, essential capital to add native support for aria2c or wget in our beloved ytDownloader to bypass these restrictions, we hope there will be an option that can be easily and quickly activated, or deactivated in the event of a problem....I have seen YouTube limit complaints even in media players that use yt-dlp....
Thank you !

**Comment by trimechee** [comment]
@aandrew-me Ouahh I'm exploring the new version of ytDownloader and I'm really surprised!! the download speed is very high!! the download speed climbs to 430kb/s which corresponds to the maximum value of my internet subscription!

Thank you so much !
compared to other downloaders with a speed limited to 90kb/s, it's incredible, sensationally revolutionary! does ytDownloader already use aria2c or wget in the background ?

**Comment by aandrew-me** [comment]
Nothing really changed with the new version 😄
I think its your internet, sometimes your speed is good, sometimes its bad

**Comment by trimechee** [comment]
Lol :) I think YouTube is becoming more aggressive, especially with the ban on ad blockers...when I use a VPN, the download speed with the other downloader goes back to 430kb/s.....it's been several weeks since It's like that, speed without VPN is limited to 90kb/s.....I'm going to try to do other tests with our beloved ytDownloader, particularly with HD streams and dash streams :)
