### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by richardstevenhack** [aandrew-me/ytDownloader#168]
**Description**
Suggest the ability to load a list of Youtube URLs from a text file from the local system, then treat the list as a playlist and download each of the URLs in turn, possibly also applying the range feature to the list.

I use Media-Downloader which can do this.  I go through my list of subscribed Youtube channels every day, and copy and paste the URLs of each video of interest into a text file. I save the text file on my system, call up Media Downloader, right click, select the "Get List From File" option, enter the file name, hit Download and off it goes. 

Currently I have an issue with Media Downloader in that my platform, openSUSE Tumbleweed, has changed the way it handles the installed yt-dlp in such a way that Media Downloader can't determine the current version. 

If Youtube Downloader Plus could do the same bulk downloads as Media-Downloader, while being an AppImage or a Flatpak that would be an advantage as the yt-dlp version would be hidden from the system. Presumably you update the AppImages and Flatpaks as the version of yt-dlp changes. I wouldn't have to worry about Tumbleweed altering the yt-dlp or python environment.

**Comment by aandrew-me** [comment]
The feature is already planned. I will add the feature when I get time. What you're doing is automation and you know that when it comes to automation, the terminal is a great choice.
You can use this option in yt-dlp

```
-a, --batch-file FILE           File containing URLs to download ("-" for
                                stdin), one URL per line. Lines starting
                                with "#", ";" or "]" are considered as
                                comments and ignored
```

**Comment by aandrew-me** [comment]
I will close this since there is already an issue https://github.com/aandrew-me/ytDownloader/issues/126

**Comment by richardstevenhack** [comment]
I already do use bash scripts at the command line with yt-dlp. So no problem there. But there are some advantages to having a GUI utility for such things, which is why I primarily use Media-Downloader. But if you do the same for Youtube Downloaded Plus, I'd definitely be interested in switching or using both. Thanks.
