### ISSUE TITLE
[BUG] download folder cannot be selected in playlist download mode

### ISSUE THREAD

**Issue by soredake** [aandrew-me/ytDownloader#172]
**Bug Description**
Download folder cannot be selected in playlist download mode.

**To Reproduce**
1. Have windows 11 Pro.
2. Install ytdownloader from winget `winget install -h aandrew-me.ytDownloader`
3. Paste any playlist and try to change download folder.
4. Fail.

**Screenshots**

https://github.com/aandrew-me/ytDownloader/assets/5204968/c99cbbd9-cf15-460e-bf5b-04f902f68d3e

**Info (please complete the following information):**
 - Operating system: Windows 11 Pro 23H2
 - App version: 3.15.0
 - Package version (flatpak/snap/other): 3.15.0

**Comment by aandrew-me** [comment]
I checked and its a plain simple bug, should be fine in next update
