### ISSUE TITLE
[Feature Request] support for downloading audio tracks other than default

### ISSUE THREAD

**Issue by soredake** [aandrew-me/ytDownloader#173]
**Description**

YouTube have support for multiple audio tracks, but ytdownloader does not have a way to select them for download, example video with multiple audio tracks: https://www.youtube.com/watch?v=HwAPLk_sQ3w

![изображение](https://github.com/aandrew-me/ytDownloader/assets/5204968/d0c230f5-de0c-499d-a913-9844074c32fc)

**Comment by aandrew-me** [comment]
Working on it
