### ISSUE TITLE
[BUG] File path can't handle paths with apostrophes

### ISSUE THREAD

**Issue by Noah6544** [aandrew-me/ytDownloader#176]
**Bug Description**
- Throws an error if I try to use my default path of "C:\Users\Noah's....\Downloads" which has an apostrophe (a bad choice I made years ago).
- I even change the path to "C:\Temp" or something to avoid my bad Windows User path, but it still throws the same error.

**To Reproduce**
1. Have a Windows User Account (in the path as well) that has an apostrophe.

**Screenshots**
Error:
![image](https://github.com/aandrew-me/ytDownloader/assets/56573280/4dfa5880-d621-4963-aa16-45f7f1535bd6)
My Path (I might not be doing/saving it right):
![image](https://github.com/aandrew-me/ytDownloader/assets/56573280/877694f4-3808-4a08-a07b-161e34a64e2d)

**Info (please complete the following information):**
 - Operating system: Windows 10
 - App version: 3.15.0
 - Package version (chocho): 2.2.2

**Comment by aandrew-me** [comment]
Interesting bug..

**Comment by aandrew-me** [comment]
The apostrophe is not the problem. It's the space in your username that's causing the problem

**Comment by aandrew-me** [comment]
Let me know
