### ISSUE TITLE
[Feature Request] Why do I need to download files for the first run on windows

### ISSUE THREAD

**Issue by muyiacc** [aandrew-me/ytDownloader#177]
**Description**

Failed to download necessary files. Please check your network and try again

Multiple attempts failed

![图片](https://github.com/aandrew-me/ytDownloader/assets/115904774/ba659824-9aa7-4dc9-b01d-92591138b983)

Can you help me solve it? Thank you

**Comment by aandrew-me** [comment]
It downloads yt-dlp, its could be failing because app cant access the internet. Did you block its access to internet?

**Comment by muyiacc** [comment]
No, I can connect to the network. I didn't do any extra actions from installing it

**Comment by aandrew-me** [comment]
Did Windows firewall show any pop-up?

**Comment by muyiacc** [comment]
I just tried running `winget install yt-dlp` in powershell and it still doesn't solve the problem.

![图片](https://github.com/aandrew-me/ytDownloader/assets/115904774/7965c213-e6b5-4cef-a156-2bf242ef7390)

**Comment by aandrew-me** [comment]
Did you install ytDownloader from widget?

**Comment by muyiacc** [comment]
No, I installed it via YTDownloader_Win.exe.

**Comment by muyiacc** [comment]
![图片](https://github.com/aandrew-me/ytDownloader/assets/115904774/85c1458a-2924-488b-8890-d71e0a86dd31)

**Comment by muyiacc** [comment]
I just restarted my computer and it seemed to work while I was waiting

![图片](https://github.com/aandrew-me/ytDownloader/assets/115904774/21197aca-d69f-4e0f-be32-ed762de09b46)


I'm extremely grateful.

**Comment by aandrew-me** [comment]
I will keep the 'restarting the computer' thing in mind next time

**Comment by aandrew-me** [comment]
Have a nice day/night!
