### ISSUE TITLE
[BUG] Can't able to download from websites that requries login as app can\t find cookies database

### ISSUE THREAD

**Issue by rahmanshaber** [aandrew-me/ytDownloader#183]
**Bug Description**
I am getting this error when i try to download from twitter or other similar ebsite that requries account login. i enabled and disable the cookie setting but still no luck.
error was about it can\t access firefox cookies.

app works fine in v15, as i reverted back to that version in flatpak. Now i am able to download from website that requires account login, like twitter. I used this guide to revert https://itsfoss.com/downgrade-flatpak-packages/

**To Reproduce**
1. 

**Screenshots**

**Info (please complete the following information):**
 - Operating system: fedora
 - App version: 16
 - Package version (flatpak/snap/other): 16

**Comment by aandrew-me** [comment]
Right, permissions were restricted in one of recent updates for security purposes. Before, app had permission to access home directory, now it doesn't. You can enable home directory permissions with flatseal and it should work fine again

**Comment by rahmanshaber** [comment]
Can you please add that solution in the app maybe, it will be really helpful.
thanks for this awesome app and quick response.

**Comment by aandrew-me** [comment]
> Can you please add that solution in the app maybe, it will be really helpful. thanks for this awesome app and quick response.

Yes I am thinking about where to add. :)

**Comment by rahmanshaber** [comment]
maybe below the cookie settings, saying "if using flatpack, need to have more permission and that can be done using flatseal"

**Comment by aandrew-me** [comment]
Yeah right, I will show that text only for flatpak users. For now I am adding it to package description on flathub.

**Comment by rahmanshaber** [comment]
Hi, I also noticed that new version can't able to show format of a video from website like twitter, but old v15 does. 
when the format dosen't show up and clicking download results failed download

**Comment by aandrew-me** [comment]
Yes I found the problem, thanks for letting me know, should be fine in next update.

**Comment by aandrew-me** [comment]
Update has been released, soon will be available, check if everything works fine

**Comment by rahmanshaber** [comment]
Yes, it's fixed now, and the permission thing settings menu is a big welcome. Thanks a lot.
