### ISSUE TITLE
[Feature Request] Kill yt-dlp and ffmpeg processes after canceling download

### ISSUE THREAD

**Issue by soredake** [aandrew-me/ytDownloader#186]
**Description**
If you cancel the download from ytdownloader those process will still be running.

**Comment by aandrew-me** [comment]
I don't know how that's possible, they can't just run if download is cancelled, because cancelling download automatically terminates the process and I tested it too.

**Comment by soredake** [comment]
On my machine, 1 or 2 times out of 10 processes are still running after cancelling the download, don't know how to reliably reproduce this.
