### ISSUE TITLE
set proxy

### ISSUE THREAD

**Issue by mfaridi1394** [aandrew-me/ytDownloader#187]
**Description**
Hi,
How I cant set proxy for this application for download ?

**Comment by aandrew-me** [comment]
Hello
https://github.com/aandrew-me/ytDownloader/issues/150
Create a text file, put the proxy test in it, like `--proxy http://localhost:8080`, then select the file from Preferences -
<img width="559" alt="image" src="https://github.com/aandrew-me/ytDownloader/assets/66430340/cc10c6cd-2eaa-46bf-ab39-fd8afc9e144a">

**Comment by mfaridi1394** [comment]
> --proxy http://localhost:8080

Thanks
If I want  use  socks5 , what I must put in config file?

**Comment by aandrew-me** [comment]
Example
`— proxy socks5://user:pass@127.0.0.1:1080/`

**Comment by mfaridi1394** [comment]
> Example `—proxy socks5://user:pass@127.0.0.1:1080/`

config file does not work m because I get connection time out error

**Comment by aandrew-me** [comment]
You're likely doing something wrong, for example I used a public socks5 proxy from [here](https://spys.one/en/socks-proxy-list/),
so my config file looked like this
```
--proxy socks5://142.54.228.193:4145
```
And it worked without any problem

**Comment by mfaridi1394** [comment]
> You're likely doing something wrong, for example I used a public socks5 proxy from [here](https://spys.one/en/socks-proxy-list/), so my config file looked like this
> 
> ```
> --proxy socks5://142.54.228.193:4145
> ```
> 
> And it worked without any problem

I got this error
`
		URL: https://www.youtube.com/watch?v=nb5oYkF3bI8
		
		ERROR: [youtube] nb5oYkF3bI8: Unable to download API page: (, 'Connection to www.youtube.com timed out. (connect timeout=20.0)') (caused by TransportError("(, 'Connection to www.youtube.com timed out. (connect timeout=20.0)')"))

		`

**Comment by aandrew-me** [comment]
Well that means likely something is wrong with your proxy. If you are using a public proxy, I may try it, otherwise I cant help

**Comment by mfaridi1394** [comment]
> Well that means likely something is wrong with your proxy. If you are using a public proxy, I may try it, otherwise I cant help

I set this proxy on another application and work like charm

**Comment by aandrew-me** [comment]
Did you try accessing YouTube with your proxy?

**Comment by mfaridi1394** [comment]
> Did you try accessing YouTube with your proxy?

I have another program for download from youtube and I set this proxy on it and work

**Comment by aandrew-me** [comment]
How does your config file look like?
(Remove sensitive details)

**Comment by mfaridi1394** [comment]
> How does your config file look like? (Remove sensitive details)

Hostname/IP:127.0.0.1
Port: 8080
ProxyType: Socks5 Proxy

**Comment by aandrew-me** [comment]
So your config file should look like this
```
--proxy socks5://127.0.0.1:8080
```

**Comment by mfaridi1394** [comment]
> So your config file should look like this, if it is how you mentioned
> 
> ```
> --proxy socks5://127.0.0.1:8080
> ```

I set this but I get timeout error

**Comment by aandrew-me** [comment]
Try with a different proxy, like this one
```
--proxy socks5://142.54.228.193:4145
```
See if it works for you

**Comment by aandrew-me** [comment]
Hm ok I am taking a look at the issue

**Comment by aandrew-me** [comment]
Hm I think I know your problem, you have to wait till the next update :(
Thanks for creating the issue

**Comment by aandrew-me** [comment]
It should work after next update. Then use this in config file
```
--no-check-certificate --proxy socks5://127.0.0.1:8080
```

**Comment by mfaridi1394** [comment]
> --no-check-certificate --proxy socks5://127.0.0.1:8080

OK, thanks I will wait for your next update

**Comment by aandrew-me** [comment]
Update will be available today, soon

**Comment by aandrew-me** [comment]
And I will likely add a proper proxy option in settings too later

**Comment by mfaridi1394** [comment]
> And I will likely add a proper proxy option in settings too later

Thanks

**Comment by aandrew-me** [comment]
Did you get to try?

**Comment by mfaridi1394** [comment]
> Did you get to try?

Thanks
after update and install new version problem solved and I can download from youtube.

Thanks
again

**Comment by aandrew-me** [comment]
Awesome!
