### ISSUE TITLE
after some crash

### ISSUE THREAD

**Issue by mfaridi1394** [aandrew-me/ytDownloader#189]
I use Manjaro Linux and install this application
In preference of this application I change download folder and read config file from different location.
But sometimes these options back to default and sometimes can not find config file.

**Comment by aandrew-me** [comment]
I have specifically created template for bug report - https://github.com/aandrew-me/ytDownloader/issues/new?assignees=aandrew-me&labels=bug&projects=&template=bug_report.md&title=%5BBUG%5D

**Comment by mfaridi1394** [comment]
Thanks all Guys, after new update issue fixed
