### ISSUE TITLE
A file isn't downloaded when there's a file with the same name

### ISSUE THREAD

**Issue by carbonfiberdev** [aandrew-me/ytDownloader#190]
**Bug Description**
Title

**To Reproduce**
1. **Download a file with name XYZ**
2. **Download a different file with name XYZ**

**Info (please complete the following information):**
 - Operating system: **Debian GNU/Linux 12 (bookworm) x86_64**
 - Desktop manager: **Xfce4**
 - File manager: **Thunar**
 - App version: **2024.1.10**
 - Package version (flatpak/snap/other): **snap**

***************************************************************************************************************
 
![bug1](https://github.com/aandrew-me/ytDownloader/assets/129768602/ae8c736c-e3c2-4c9d-8ae8-0acdaf555474)
![bug2](https://github.com/aandrew-me/ytDownloader/assets/129768602/72689456-c536-4568-a11a-b1d1938f260e)

video links i was trying to download if it may help you
https://www.youtube.com/watch?v=4zeUOUo09Hs&t=7s
https://www.youtube.com/watch?v=ZVb_yKMivqo&t=8s
 
***************************************************************************************************************
Hi, thanks all of your efforts very appreciated, i use your app all day and really like it.
I encountered that small problem, don't know if it's caused by only my system and wanted to create a bug report, because i don't know electron apps so couldn't figure out where the problem came out by looking into code.

**Comment by aandrew-me** [comment]
Well its not a bug. Its like this because if for some reason you couldn't complete the download, it will resume from there. 
If you need you can easily change the file name before downloading.

**Comment by carbonfiberdev** [comment]
Hi thanks for the answer, i made a mp3 list and started to download them, luckly there was 2 different file but with same name in my list, the one was downloaded and processed seamlessly then the other one downloaded but it got stuck at processing stage and i thought that's because they have same file names. I'll try to re-produce the error and will edit my post with a screenshot as soon as possible. Thanks.

**Comment by carbonfiberdev** [comment]
i just uploaded images about the error message

**Comment by aandrew-me** [comment]
Thanks for the provided information, I will check

**Comment by aandrew-me** [comment]
I will add the id to the name so that there aren't conflicts

**Comment by carbonfiberdev** [comment]
Thanks for your efforts, changed the latest version and the issue is no longer exits so i think we can close that, what do you think ? :)

> https://www.youtube.com/watch?v=ZVb_yKMivqo&t=8s

Thanks again just tried the app again after these latest changes and downloading the two files i mentioned earlier, the problem has been fixed. I think we can close the issue request, what u you think ?. Thanks.

**Comment by aandrew-me** [comment]
Well I didn't even push an update, but I assume you are building it yourself?

**Comment by carbonfiberdev** [comment]
> Well I didn't even push an update, but I assume you are building it yourself?

your update is here 
![update1](https://github.com/aandrew-me/ytDownloader/assets/129768602/ea683e57-9fcf-4783-aa5d-3ee392507d63)

**Comment by aandrew-me** [comment]
Yes in git

**Comment by carbonfiberdev** [comment]
I mean, I just wanted to say that with your latest update the problem is no longer exists be it on git.
