### ISSUE TITLE
TikTok video downloads fail because video format dropdown box is empty

### ISSUE THREAD

**Issue by Abdull** [aandrew-me/ytDownloader#192]
**Bug Description**
sample TikTok video: https://www.tiktok.com/@ale.loko/video/7339573667648785670

**To Reproduce**
* Provide sample TikTok video link https://www.tiktok.com/@ale.loko/video/7339573667648785670
* The download configuration dialog appears. The "Video > Select Format" dropdown box is empty: there is no format to choose from.
* After clicking "Download", ytDownloader eventually fails with the error message "*Some error has occured. Hover to see details*"
* Investigating the *Developer Tools* console (<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>I</kbd>) reveals the problem: probably because no format was selectable, the `-f` format option is empty, and the `-o` output filename has the filename extension `.undefined`:
    > `Spawn args:"/home/Abdull/.ytDownloader/ytdlp"   -f  -o "/home/Abdull/Downloads/youtube-downloader-plus/Parte 2 removedor  [7339573667648785670].undefined" --ffmpeg-location "/app/main/resources/app/html/../ffmpeg"   --no-playlist --embed-metadata      --no-mtime "https://www.tiktok.com/@ale.loko/video/7339573667648785670"`

**Screenshots**
![image](https://github.com/aandrew-me/ytDownloader/assets/529862/8e3c70d9-c6c8-41d3-a1aa-f61a4380f920)
![image](https://github.com/aandrew-me/ytDownloader/assets/529862/e0765e06-b221-4b28-9876-9f125fda555a)

**Info (please complete the following information):**
 - Operating system: Debian 12 bullseye
 - App version: 3.17.2
 - Package version (flatpak/snap/other): flatpak

**Comment by aandrew-me** [comment]
Thanks for the issue, it will be fixed in next update

**Comment by Abdull** [comment]
I just updated to *ytDownloader `3.17.3`* [from Flathub](https://flathub.org/apps/io.github.aandrew_me.ytdn) and can report that this issue is fixed now. Thank you very much!
