### ISSUE TITLE
[Feature Request] Ability to trim a video

### ISSUE THREAD

**Issue by thibaultmol** [aandrew-me/ytDownloader#194]
It would be nice if you could instantly select a start and end section of the video so the end result is also directly cut to the section you want (in case you want a specific section of a video)

**Comment by thibaultmol** [comment]
btw, it's even possible to only download the required sections: https://github.com/yt-dlp/yt-dlp/issues/2220

**Comment by aandrew-me** [comment]
Trim support is already available
