### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by mrfhsn** [aandrew-me/ytDownloader#195]
**Bug Description**
Having problem installing the application.
Application can not be opened as it can not find the .exe file
No uninstall.exe file is created. Now I can't  uninstall it.

**Screenshots**
![Screenshot 2024-03-07 011549](https://github.com/aandrew-me/ytDownloader/assets/93346328/83acf256-862d-47a9-8d0c-93f7a409e1bb)
![Screenshot 2024-03-07 011606](https://github.com/aandrew-me/ytDownloader/assets/93346328/78dbcf14-627d-4118-8e40-923297be4c54)
![Screenshot 2024-03-07 011629](https://github.com/aandrew-me/ytDownloader/assets/93346328/70639c02-5000-42d2-bd68-a9832b6142f4)

 - Operating system: Windows 10
 - App version: 3.17.3 (I also tried the earlier ones)

**Comment by aandrew-me** [comment]
That's strange. I think something in your computer is configured differently which is causing this, as I have installed on Windows 10 numerous times without problems. 
Maybe you can provide steps to reproduce this problem
