### ISSUE TITLE
[Feature Request] TikTok Video without watermark or username

### ISSUE THREAD

**Issue by Skaamit** [aandrew-me/ytDownloader#197]
Some other downloaders provide the option to download a clear video from TikTok without watermark.

Have you thought about adding something like this? Or I just didn't find this function in the app. I'm using the Flatpak version.

**Comment by aandrew-me** [comment]
Among the listed formats, there are already videos which don't have watermarks. I need to find a way to show that, I will try to add it. But for now you need to try downloading a couple of them and one of them should be without watermark

**Comment by Skaamit** [comment]
> Among the listed formats, there are already videos which don't have watermarks. I need to find a way to show that, I will try to add it. But for now you need to try downloading a couple of them and one of them should be without watermark

Ok. I already found it. Anyway an addition mark about this option can be handy.

Thank you.
