### ISSUE TITLE
[Feature Request] Allow multiple trims per video

### ISSUE THREAD

**Issue by Sphirye** [aandrew-me/ytDownloader#198]
I believe it would be worth to allow multiple time-ranges when downloading a video (which implies saving a diferent file per trim).

![imagen](https://github.com/aandrew-me/ytDownloader/assets/68203934/f4a38cad-1e03-4121-829f-6e42cc262c31)

Plus, it would be cool adding the given time-range to the filename, if you try downloading multiple clips one by one from the same source, you'll see these will overwrite the previous file, which sucks since you notice that all of your clips have been overwriting themselves the whole time.

**Comment by aandrew-me** [comment]
Fair point, I will implement it

**Comment by aandrew-me** [comment]
Check if its working properly

**Comment by Sphirye** [comment]
![imagen](https://github.com/aandrew-me/ytDownloader/assets/68203934/31d96dec-da08-4f08-9e06-de38be116190)
Seems to be working okay, thank you!
