### ISSUE TITLE
[BUG] Not downloading necessary files in OpenSUSE Tumbleweed

### ISSUE THREAD

**Issue by adityanav123** [aandrew-me/ytDownloader#201]
**Bug Description**
I downloaded the AppImage file today and whenever I start it, it shows the message: Please wait, necessary files are being downloaded. and then this error message is there.
The network is fine with other applications, not sure why this download is getting blocked.

**Screenshots**
![image](https://github.com/aandrew-me/ytDownloader/assets/39703082/63b16a44-ff18-466d-9bcd-595501f4c32a)

**Info**
 - Operating system: Linux: OpenSUSE Tumbleweed
 - App version: 3.17.3
 - Package version (flatpak/snap/other): AppImage

**Comment by aandrew-me** [comment]
Maybe try with a vpn. Or maybe there is some file access permission related problem, so you may try downloading from [flatpak](https://flathub.org/apps/io.github.aandrew_me.ytdn)?

**Comment by adityanav123** [comment]
Hi, thanks for the reply, I did download from flatpak but the issue was the same, I'll will try with `vpn` though, earlier I was using Manjaro it was working there perfectly.

**Comment by aandrew-me** [comment]
I see, then its most likely related to the network

**Comment by adityanav123** [comment]
Yes, The issue was with the network only, not sure why with opensuse, i connect to von and it downloaded the files. now it works without the vpn. 👍

**Comment by aandrew-me** [comment]
Glad to hear!
