### ISSUE TITLE
setting duration in audio sample

### ISSUE THREAD

**Issue by toxeekmeelk** [aandrew-me/ytDownloader#203]
Hello!!

I wrote an idea here https://github.com/aandrew-me/ytDownloader/discussions/200 but I still have no answer. I thought it was because you're overbooked but I saw you answered another later post... So maybe it's because I'm french (joke)

Anyway, this is what i wrote a little month ago :

<i>Hello,

<i>I'm french so please excuse my possibly damaged English

I tried to set the duration of an audio sample (from a song) but it extracts the all track. Is there a way to extract only the selected part you want (by setting start and end) to make an audio sample as it seems to be possible with video ?</i>

I promise I'll do my best to respect English grammar as well as possible ;)

**Comment by aandrew-me** [comment]
Hello, I forgot to reply.

For now its not possible
