### ISSUE TITLE
[Feature Request] The video download format can only be selected as MP4

### ISSUE THREAD

**Issue by muyiacc** [aandrew-me/ytDownloader#210]
**Description**
Hello author, why is it not supported to choose different formats after the update, and why is it removed

**Comment by aandrew-me** [comment]
It has been done to simplify the user interface. You can enable it from preferences
<img width="559" alt="image" src="https://github.com/aandrew-me/ytDownloader/assets/66430340/74cac21f-eb99-455d-b89c-29f71bc0515e">

**Comment by muyiacc** [comment]
Oh, thank you. I haven't been using it and haven't noticed it. Thank you again for resolving it. You can close this issuse now. Best wishes to you
