### ISSUE TITLE
Add new universal awesome extract audio preset to fix current  problems and bugs of extract audio feature : " -f bestaudio/worst -x "

### ISSUE THREAD

**Issue by trimechee** [aandrew-me/ytDownloader#211]
Hello, thank you so much for the new amazing version or YtDownloader ! 🥇 💯 

Please once again I come back to the thorny question of audio extraction from the video, I try to download only the audio from the video to save space on a small entry-level ssd, so I choose the "m4a" format in the settings of our beloved YtDownloader and by choosing the "extract audio" option of YtDownloader, YtDownloader downloads the dailymoton video but sends me an error with this video !

https://www.dailymotion.com/video/x8y5cnc

Please to fix these audio extraction errors and especially to resolve the problem that YtDownloader does not remember that we hope to extract the audio from the video which has the worst video quality, I found a rare fantastic revolutionary audio preset which fixes all the problems of audio extraction for all websites and we no longer need to change the video and audio format and quality with each download, so please we hope our beloved YtDownloader will add functionality that let us to add our own personalized custom presets or modify the behavior by default of "extract audio" feature which downloads the best youtube audio quality (if we choose the "worstaudio" preset with youtube, the download is very slow so it becomes necessary to use the "-f bestaudio" preset which offers a balanced quality of 128kb/s and a very fast download compared to the very slow download of the "worsaudio" preset) 

and if the video does not have an independent dash audio stream like dailymotion and facebook videos, then please automatically use the " -f worst -x " preset, so please we hope Mr Andrew will allow us to add our own universal audio extraction preset " -f bestaudio/worst -x " or YtDownloader adds by default or an option to activate this universal audio extraction preset " -f bestaudio/worst -x " which allows us to extract audio from all sites without problems and quickly, thank you very much !

**Comment by Muxutruk2** [comment]
This issue has not recived any lights, I will try my best to fix this issue. @trimechee Could you point me to the lines of code where the quality is set?

**Comment by aandrew-me** [comment]
I will try to fix it

**Comment by trimechee** [comment]
Great, thank you :)

**Comment by aandrew-me** [comment]
I tried downloading the audio with both normal and worst quality. I had no errors


https://github.com/aandrew-me/ytDownloader/assets/66430340/a2df1e85-6421-4bdf-8fe5-087f2938a236

**Comment by trimechee** [comment]
Yes I didn't say there is an error but it's an innovative preset invented by another downloader, I found it annoying to always have to change presets because I download the audio from youtube, facebook and dailymotion videos, the preset worstaudio works with youtube but the download is very slow and throttled at 40kb/s, so unless YtDownloader uses aria2c, the bestaudio preset seems to be a better preset for audio extraction because even if its size is larger, the download is much faster...

and the worst -x preset will be a universal preset reserved for facebook and dailymotion and thousands of other sites when the bestaudio preset does not work....so my request was a suggestion for improvement to universally extract audio from videos ...Thanks a lot !

**Comment by trimechee** [comment]
Ahhh I forgot there is an error with dailymotion....yt-dlp has made several updates since my issue, and even a new version of ffmpeg has appeared...I will do some tests again...

**Comment by trimechee** [comment]
Mr @aandrew-me , I have the same error, Mr @aandrew-me , please wait until the download and audio extraction are finished, YtDownloader will display error message: "error postprocessing, unable to embed using ffprobe ffmpeg, ffprobe not found, please install or provide the path using.....ffmpeg location " ....

I hope YtDownloader will add a "quick audio extraction without conversion" option because there are so many audio format choices and we don't know which audio format to choose for extraction fastest audio, the audio format doesn't matter, the most important thing is the fastest audio extract especially if it's a playlist, thank you very much !

**Comment by aandrew-me** [comment]
"Quick audio extraction without conversion" is basically this part
<img width="675" alt="image" src="https://github.com/aandrew-me/ytDownloader/assets/66430340/da7b0ab8-1f20-42df-8431-2d1d7bf46100">

**Comment by aandrew-me** [comment]
I waited for the extraction, I didn't get errors. What OS are you using? Tell me how I can reproduce the error

**Comment by trimechee** [comment]
Thank you for your help, is there a way to copy and send logs ? i use windows 10 os last version, it's bizarre, it seems I don't have the same options and arrangements that you display in your screenshot, I chose worst quality in the options of the audio category, here a scrrenshot : 
![Capture](https://github.com/aandrew-me/ytDownloader/assets/76402212/43b5395c-50b4-47bc-b707-91131f92a2ca)

**Comment by aandrew-me** [comment]
The screenshot I sent is from a video of youtube. Dailymotion doesn't provide separate audio streams. So you have to extract audio from video. Now regarding your error, I will test on windows machines to find out the problem

**Comment by trimechee** [comment]
Great !! Thank you so much for your precious help :) 🥇 💯

**Comment by trimechee** [comment]
Mr @aandrew-me , great news ! I do another test, and despite  YtDownloader is displaying the same error message, I check my download folder and there is an audio file in m4a format and I check with a media player and it is a valid audio file! so  YtDownloader succeeded to extract the audio from the dailymotion video but the error message is weird and reduced us to error....

**Comment by aandrew-me** [comment]
Thanks for the info. Its likely because its failing to embed thumbnail

**Comment by trimechee** [comment]
Yes i think this is thumbnail bug because in my download folder, I have a jpg file with the name of the video !

**Comment by aandrew-me** [comment]
Can you please go to `%USERPROFILE%\.ytDownloader` folder. Inside it you will find `ytdlp` file. Check its size and tell me

**Comment by aandrew-me** [comment]
Its okay, you don't have to, I found the problem

**Comment by aandrew-me** [comment]
Check the latest release, should be fixed

**Comment by trimechee** [comment]
Great , thank you so much :) 💯 🥇
