### ISSUE TITLE
macOS version is only for ARM64, no Intel version

### ISSUE THREAD

**Issue by Marc66** [aandrew-me/ytDownloader#222]
The latest release (3.18) dmg and zip files only include an ARM64 binary

Can you please make a x64 version available for macOS?

**Comment by aandrew-me** [comment]
Thanks for letting me know

**Comment by aandrew-me** [comment]
Looks like the latest build for mac was build on mac with arm64 processor in github actions, that's why the binaries are arm64 binaries

**Comment by aandrew-me** [comment]
I will make a new release soon with both versions

**Comment by aandrew-me** [comment]
Should work: https://github.com/aandrew-me/ytDownloader/releases/download/v3.18.1/YTDownloader_Mac_x64.dmg
