### ISSUE TITLE
Previous voluminous updaters are not deleted after uninstallation

### ISSUE THREAD

**Issue by trimechee** [aandrew-me/ytDownloader#223]
Hello, we can buy an entry-level laptop and the SSD has a size of only 128Gb, ​​so disk space can become precious I have already talked about this problem when you do an update, ytDownloader keeps the updater from the old version which weighs 128MB, I uninstall ytDownloader hoping that the old updaters will be deleted and I check in the hidden Windows folders but unfortunately, the folder which contains the old ytDownloader updaters are not deleted even after uninstallation, we hope then uninstallation, ytDownloader removes the old updaters which can take up a lot of space especially in a limited SSD, laptops and Chrome Books have SSDs of only 32Gb or 64Gb, so we can reinstall ytDownloader without the old bulky updates, thank you !

**Comment by aandrew-me** [comment]
I'll close it since this issue already exists - https://github.com/aandrew-me/ytDownloader/issues/134
