### ISSUE TITLE
Video title only gets the original title

### ISSUE THREAD

**Issue by muyiacc** [aandrew-me/ytDownloader#224]
**Description**
Hello, sorry to bother you.

When downloading a video, the obtained title will be added with the video id at the end, instead of the pure video title. The resulting problems are: not conducive to synchronization, local deduplication and storage, and the purity of the video file name.

I hope to get only the video title!

In addition, I saw someone say in #190 that different videos with the same title cannot be saved. I think very few videos will use the same title, which is not conducive to reading. If possible, I hope these two can be solved.

**Comment by aandrew-me** [comment]
I don't understand any of the problems you mentioned.
And you can always modify the title before downloading.

**Comment by muyiacc** [comment]
Well, I modified it manually and it wasn't a big deal.
