### ISSUE TITLE
[BUG] YtDownloader Windows install  Trojan ? 

### ISSUE THREAD

**Issue by zeitounmax** [aandrew-me/ytDownloader#226]
Hi Aandrew-me, 
i have a problem with a update with your application.
My Windows defender say it's a dangerous problem (Casdet!rfn )

It's normal or not ?  
Thank you !

![image](https://github.com/aandrew-me/ytDownloader/assets/120447954/aa25bc5a-e7a6-41df-9ab2-9f1d5c63926b)

**Comment by zeitounmax** [comment]
That's why I didn't understand because I've been using your application for a while now and I'm really satisfied. For security and (especially Windows Defender) I'm using kapersky to see if there's anything there.  It's probably a Windows Defender error, so I thought I'd pass on the info to you, and above all, I was surprised by the warning.

**Comment by aandrew-me** [comment]
Yeah I appreciate your concerns. I'll leave the issue open for some days so that if someone faces similar issues, they can see it.

**Comment by cbellosoto** [comment]
I am also facing the same issue. It seems to not like the renaming. 

If users are unable to get past the WindowsDefender Quarantine fo any reason, they can simply 'Uninstall', Download the new release from GitHub, then Install the New release, only need to Trust the Publisher, which is expected.

Hope this helps. 

I wonder if there is a way to inform microsoft this app/update is not a Trojan.
