### ISSUE TITLE
[Feature Request] Option to reverse the order of the list

### ISSUE THREAD

**Issue by slumbergod** [aandrew-me/ytDownloader#228]
If you run out of coding ideas for this project I would like an option to reverse the order of the download list so that newly added downloads are added at the top. I typically end up with a huge list of downloads and to see if a new file has started downloading correctly I have to scroll through all of the download history to check. Just a wish list item :)

**Comment by aandrew-me** [comment]
I think that's more on the side of the "File Manager". There is likely an option to sort by **Last Modified** or simply in **Descending** order
