### ISSUE TITLE
[BUG] MacOS GUI disappears when moving app from installed location 

### ISSUE THREAD

**Issue by FredsMedia** [aandrew-me/ytDownloader#234]
**Bug Description**

**To Reproduce**
1. Open application in one location on fresh install (e.g. Desktop)
2. Close app and move to a different location (e.g. Applications Folder)
3. Open app
4. No main menu GUI

**Screenshots**
<img width="912" alt="Screenshot 2024-08-22 at 7 35 36 pm" src="https://github.com/user-attachments/assets/3c8b4027-2f3e-4605-a360-8243fe4a3ba0">

**Info (please complete the following information):**
 - Operating system: MacOS
 - App version: 3.18.1
 - Package version (flatpak/snap/other): N/A (The intel mac app)

**Comment by FredsMedia** [comment]
If i copy it _back_ to the desktop there is still no GUI. I have also tried deleting the application support folder and relaunching but that hasn't helped.

**Comment by aandrew-me** [comment]
Which file are you downloading, . dmg or . app?

**Comment by FredsMedia** [comment]
i got the x64 .dmg

**Comment by aandrew-me** [comment]
I tested on an intel Mac just now, it loads but it just takes a lot of time. It took 35 seconds for that button to appear.
I will look into why its happening

**Comment by FredsMedia** [comment]
huh, so it does. It doesnt seem to use heaps of resources...

**Comment by aandrew-me** [comment]
Apparently there some issue with the yt-dlp executable. That's what's causing it.

Its executing the command
```
/Users/$USER/.ytDownloader/ytdlp --version
```

Which is taking a very long time

**Comment by FredsMedia** [comment]
yep. I ran that myself and it about matches the startup time.

**Comment by aandrew-me** [comment]
Yeah seems to be some issue with the newer versions, I tried with an older version and it ran fast

**Comment by aandrew-me** [comment]
I will see what I can do

**Comment by aandrew-me** [comment]
I have opened an issue there, you may add a comment too
https://github.com/yt-dlp/yt-dlp/issues/10826

**Comment by FredsMedia** [comment]
Welp, it looks like they aren't doing/can't do anything about it. Would there be a way to skip the version check?

**Comment by aandrew-me** [comment]
Well the issue isnt just the version check, any command executed with yt-dlp will be slow, getting video info, downloading video...

**Comment by aandrew-me** [comment]
Thumbs down to Macos, I guess I will have to take a different approach with Mac.
Can you please check
`python3 --version`

**Comment by FredsMedia** [comment]
> Thumbs down to Macos, I guess I will have to take a different approach with Mac. Can you please try executing-
> 
> ```
> python3 --version
> ```

Sure.

**Comment by aandrew-me** [comment]
Great thanks! Did you install python by yourself or was it already there?

**Comment by FredsMedia** [comment]
I _believe_ that version was preinstalled

**Comment by aandrew-me** [comment]
Great, thanks

**Comment by aandrew-me** [comment]
Then this issue should be fixed in next update

**Comment by FredsMedia** [comment]
What are ya planning to do?

**Comment by aandrew-me** [comment]
I will switch to that for mac, the drawback will be that embedding of thumbnails will likely not be possible

**Comment by FredsMedia** [comment]
I know macOS provides a version of python, I’m not sure what version it installs as I have installed a newer version of python myself. It _should_ still work though.

**Comment by aandrew-me** [comment]
As far as I know, it requires python 3.8 or greater. I will have to add that to info

**Comment by FredsMedia** [comment]
Lemme check the default version real quick

**Comment by FredsMedia** [comment]
<img width="697" alt="Screenshot 2024-08-25 at 8 44 38 pm" src="https://github.com/user-attachments/assets/b6ab7f44-95b9-4583-80b9-068e8a8791a7">
It seems to be python 3.9.6, so it should work.

**Comment by aandrew-me** [comment]
Okay great

**Comment by FredsMedia** [comment]
I mean if it doesn’t work, you’ll know pretty quick 😅

**Comment by FredsMedia** [comment]
Yep, it seems like it's working fine (but signifcantly faster ofc)

**Comment by aandrew-me** [comment]
Awesome!
