### ISSUE TITLE
with long playlists index number is off

### ISSUE THREAD

**Issue by splace** [aandrew-me/ytDownloader#235]
**Bug Description**
download just the last few of long playlist gives index number different to Youtube's

(https://www.youtube.com/playlist?list=PLsY30fLfDNuIUJDBusf0cKVPKVQIig75_)

this playlist gives indexes 3 (more than) too youtube.

![image](https://github.com/user-attachments/assets/b7427788-533d-4d88-9b04-c825023e0ce7)

![Screenshot From 2024-08-23 23-35-52](https://github.com/user-attachments/assets/35456163-8573-4dce-a8bf-48db64e4b998)

**Comment by aandrew-me** [comment]
I have added something which I think should fix it, check in next update if it has been fixed
