### ISSUE TITLE
[BUG] Does it work on ARM Mac?

### ISSUE THREAD

**Issue by Guuustav** [aandrew-me/ytDownloader#240]
I have installed the last two versions (YTDownloader_Mac_arm64) both dmg and zip and they do not work on my Macbook Pro M1 Max. When opened it says the package is corrupted.
![Screenshot 2024-09-04 at 09 01 56](https://github.com/user-attachments/assets/9267fbd4-2492-41b1-a5ba-ad482235a6da)
 - Operating system: macos Monterey 12.7.6
 - App version: 3.18.2 and 3.18.1
 - Package version: YTDownloader_Mac_arm64

Thanks in advance.

**Comment by aandrew-me** [comment]
Unfortunately I can't test in on an m1 mac. However it works fine for me on an intel mac. It could be related to antivirus. 
https://discussions.apple.com/thread/253714860?sortBy=rank
Maybe try this command:
```
xattr -c <path/to/application.app>
```

**Comment by superlativ0** [comment]
Perfect @aandrew-me. That was the problem. Then the application opened on the first try. Sorry for the inconvenience and thank you very much.

**Comment by Guuustav** [comment]
Perfect @aandrew-me. That was the problem. Then the application opened on the first try. Sorry for the inconvenience and thank you very much.
