### ISSUE TITLE
[BUG] Download for Windows leads to 404 Error

### ISSUE THREAD

**Issue by irbcallmefynn** [aandrew-me/ytDownloader#242]
**Bug Description**
When selecting the "Download for Windows" button, it leads to an 404 Error screen.
**To Reproduce**
1. Click on the button that says "Download for Windows" located next to the "Download on Flathub" button and above the "Download from Chocolatey" button
**Screenshots**
![a](https://github.com/user-attachments/assets/ba63043e-7656-43e0-9162-92c349225685)
![b](https://github.com/user-attachments/assets/806ddc4e-201f-4bd8-8cd0-3e2e1267a106)
**Info (please complete the following information):**
 - Operating system: Windows
 - App version: N/A
 - Package version (flatpak/snap/other): N/A

**Comment by aandrew-me** [comment]
Thank you for letting me know
