### ISSUE TITLE
No control elements - Window pops up, no function; Linux Mint 22

### ISSUE THREAD

**Issue by ERIPECH** [aandrew-me/ytDownloader#243]
**Bug Description**
flatpak run io.github.aandrew_me.ytdn
[3:0916/072224.195158:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: Datei oder Verzeichnis nicht gefunden
Gtk-Message: 07:22:24.329: Failed to load module "xapp-gtk3-module"
[3:0916/072224.365355:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: Datei oder Verzeichnis nicht gefunden
[3:0916/072224.365396:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: Datei oder Verzeichnis nicht gefunden
Locale:de
Version: 3.18.2
bounds: { x: 801, y: 220, width: 886, height: 576 }
MESA: error: Failed to query drm device.
glx: failed to create dri3 screen
failed to load driver: iris
failed to open /dev/dri/card1: Datei oder Verzeichnis nicht gefunden
failed to load driver: iris
APPIMAGE env is not defined, current application is not an AppImage

**To Reproduce**
Install Flatpack, 
also if deleted and re-installed
tried also to update everything: dbus, mesa, mesa-utils, libgl1-mesa-dri, gir1.2-xapp-1.0

**Comment by aandrew-me** [comment]
I will check once I can

**Comment by aandrew-me** [comment]
Which edition of Linux Mint are you using?

**Comment by ERIPECH** [comment]
Linux Mint 22, Cinnamon 6.2.9, Kernel 6.8.0-45-generic, X11 Window System

**Comment by aandrew-me** [comment]
I tested running the mint on Linux Mint 22, it ran fine without issues. 

In your logs I see
```
MESA: error: Failed to query drm device.
glx: failed to create dri3 screen
failed to load driver: iris
```
Which is error related to OpenGL drivers. So there is something incorrectly configured with your graphics drivers and you may need to do some troubleshooting. These may help -
https://askubuntu.com/questions/1352158/libgl-error-failed-to-load-drivers-iris-and-swrast-in-ubuntu-20-04
https://github.com/kiwix/kiwix-desktop/issues/393

**Comment by ERIPECH** [comment]
flatpak override --user --env=LIBGL_ALWAYS_SOFTWARE=1 io.github.aandrew_me.ytdn

this solves the issue for me - thanks for your support

**Comment by aandrew-me** [comment]
Great!
