### ISSUE TITLE
[BUG] App Broken

### ISSUE THREAD

**Issue by Agent-80** [aandrew-me/ytDownloader#247]
**Bug Description**
Blank screen

**To Reproduce**
1. just open the app

**Screenshots**
![image_2024-09-20_184204595](https://github.com/user-attachments/assets/834e86e7-6625-457c-a202-ab17db0def40)
![image_2024-09-21_111912081](https://github.com/user-attachments/assets/105d3131-8ca7-4646-b578-2ec26ab35026)

**Info (please complete the following information):**
 - Operating system: Pop!_OS 22.04 LTS
 - App version: 3.18.2
 - Package version (flatpak/snap/other): flatpak

**Comment by aandrew-me** [comment]
Linux isnt Operating System. There are several distros, desktop environments. You gotta specify that

**Comment by FromRightToLeft** [comment]
I have the same issue on Linux Mint 21.3 Cinnamon 6.0.4

**Comment by aandrew-me** [comment]
> I have the same issue on the same app version from flatpak in Linux Mint 21.3 with Cinnamon 6.0.4


I had tested on a fresh install of Mint 21.3 with cinnamon and there were no issues. Send your logs from terminal. Also check this issue - https://github.com/aandrew-me/ytDownloader/issues/243

**Comment by FromRightToLeft** [comment]
Yes, it is the same problem. 

MESA: error: Failed to query drm device.
glx: failed to create dri3 screen
failed to load driver: iris

The way I was able to fix it was through Flatseal app: I've switched GPU acceleration ON. Now, it takes two seconds to switch from blank screen to operational, but it works. Tested with a random video.

Question: It used to work fine without it, what had changed?

**Comment by Adam-Ladd** [comment]
Same issue on fedora kde plasma

**Comment by Agent-80** [comment]
> Linux isnt Operating System. There are several distros, desktop environments. You gotta specify that

 its Pop!_OS 22.04 LTS

**Comment by aandrew-me** [comment]
> Yes, it is the same problem.
> 
> MESA: error: Failed to query drm device. glx: failed to create dri3 screen failed to load driver: iris
> 
> The way I was able to fix it was through Flatseal app: I've switched GPU acceleration ON. Now, it takes two seconds to switch from blank screen to operational, but it works. Tested with a random video.
> 
> Question: It used to work fine without it, what had changed?

Okay that's good, I don't yet know what changed

**Comment by aandrew-me** [comment]
> Same issue on fedora kde plasma

Launch from terminal and check your logs too

**Comment by ajyand** [comment]
I used this command but now the app is stuck on downloading necessary files for a long long time, though I could reinstall the app in few seconds.

<code>flatpak --user override --device=dri io.github.aandrew_me.ytdn</code>

**Comment by migtorr** [comment]
> I used this command:
> 
> `flatpak --user override --device=dri io.github.aandrew_me.ytdn`

Had the same issue with Vanilla OS 2.0 and that command sorted it

**Comment by aandrew-me** [comment]
Yeah looks like it requires now to add `--device=dri`. I will add it to app manifest
