### ISSUE TITLE
[Feature Request] Possible to add an option to use Invidous instances?

### ISSUE THREAD

**Issue by linlinxza** [aandrew-me/ytDownloader#248]
I'd like to avoid going to the domain youtube.com at all. And according to my PiHole server, when downloading a video, this app makes contact with YouTube directly. So, I am wondering if an option can be added to use Invidious instances.

**Comment by aandrew-me** [comment]
I don't fully get your question. Invidious is just a frontend for youtube. You're still making requests to youtube

**Comment by linlinxza** [comment]
> I don't fully get your question. Invidious is just a frontend for youtube. You're still making requests to youtube

Sure. But it's on behalf of the frontend and not me going directly to YouTube. I mean, the app, FreeTube can use an Invidious instance. So, I was just wondering.

**Comment by aandrew-me** [comment]
If I get you correctly, you want your requests to be proxied through some invidious instance. As far as I know, its not possible with yt-dlp. If you find something though, let me know

**Comment by linlinxza** [comment]
> If I get you correctly, you want your requests to be proxied through some invidious instance. As far as I know, its not possible with yt-dlp. If you find something though, let me know

We'll see. When I have time to monkey around with the command line.
