### ISSUE TITLE
[Feature Request] Extract the audio only - no video

### ISSUE THREAD

**Issue by ihtishamqabid** [aandrew-me/ytDownloader#249]
**Description**
Option to extract/convert the audio only not the video would be greatly appreciated.

**Comment by TriDefender** [comment]
you can add a script that uses ffmpeg to rip out the audio

**Comment by ihtishamqabid** [comment]
Thank you @aandrew-me and @TriDefender. Is there a way to do it in GUI mode?

**Comment by TriDefender** [comment]
@ihtishamqabid Yes, infact you can choose to download audio only, and you can also choose quality of audio. When you pasted the link there's supposed to be a download interface where you can choose the format required

**Comment by ihtishamqabid** [comment]
Oh, that's great! I must have missed it. Insha'Allah I will have a look and if I find it then I will close this thread.
