### ISSUE TITLE
[BUG] 4K format is not an option

### ISSUE THREAD

**Issue by ichthus-intero** [aandrew-me/ytDownloader#250]
**Bug Description**
When loading a video that has a 4K version available on YT, the application is not showing this as an available video format for download. 

**To Reproduce**
1. Clone the repo, cd into the directory
2. npm i
3. npm start
4. Paste example 4K video (https://www.youtube.com/watch?v=SHuogjpnu04)
5. See that the highest resolution available is 1080p, there is no 2160p

I've tried this with multiple 4K videos both my own and others like the short video example above.

**Screenshots**
<img width="411" alt="formats" src="https://github.com/user-attachments/assets/ff384371-72f2-4009-b05d-76bdc8e1a5ad">

**Info (please complete the following information):**
 - Operating system: Mac OS Ventura 13.6.6
 - App version: 3.18.2
 - Package version (flatpak/snap/other): not sure?

**Comment by aandrew-me** [comment]
![image](https://github.com/user-attachments/assets/30b0d274-2624-4dbf-8c28-8e99bd359968)
Hmm, maybe its network related?

**Comment by ichthus-intero** [comment]
Can you please share the video URL for your example image above? I will try that one.

**Comment by aandrew-me** [comment]
Indeed, you've got some weird file sizes, its likely something network related
