### ISSUE TITLE
[BUG] Not working anymore with Linux Mint 22 - Only white window.

### ISSUE THREAD

**Issue by stefan-franz** [aandrew-me/ytDownloader#252]
Only white window
Linux Mint 22
With Linux Mint 21 is was fine

![Youtube Downloader](https://github.com/user-attachments/assets/c8bd0b3d-5723-4cad-be5a-54bf677d0188)

**Comment by aandrew-me** [comment]
Check this issue - https://github.com/aandrew-me/ytDownloader/issues/247

**Comment by aandrew-me** [comment]
And this one - https://github.com/aandrew-me/ytDownloader/issues/243
