### ISSUE TITLE
[Feature Request] Custom Arguments

### ISSUE THREAD

**Issue by mid-ff-play17** [aandrew-me/ytDownloader#254]
**Description**
Hello aandrew-me!
Is there a chance that custom arguments will appear in the program?

**Comment by aandrew-me** [comment]
Hello! You can add custom arguments with config file

**Comment by aandrew-me** [comment]
I wrote about how to use it here - https://github.com/aandrew-me/ytDownloader/issues/187

**Comment by mid-ff-play17** [comment]
> I wrote about how to use it here - #187

Oh, thank you for answer!
