### ISSUE TITLE
[BUG] unable to download twitch vods

### ISSUE THREAD

**Issue by memebl14** [aandrew-me/ytDownloader#256]
when you paste the link to any twitch vod, the program doesn't show any download options

**Screenshots**
![image](https://github.com/user-attachments/assets/30b1cf8b-1573-44fa-bcf1-d7dea31b3596)

**Info (please complete the following information):**
 - Operating system: Windows 10 Pro
 - App version: 3.18.3.0
 - Package version (flatpak/snap/other): YTDownloader_Win.exe

**Comment by aandrew-me** [comment]
Can you please provide the link of the video

**Comment by memebl14** [comment]
this happens with any vod

**Comment by aandrew-me** [comment]
Okay I found the issue, I have fixed it and pushed it to master branch. It will fixed in next update

**Comment by aandrew-me** [comment]
If you want to test it, I can send the executable

**Comment by memebl14** [comment]
I'm not in a hurry, I'd ask you to take a look at the other issues I've opened: #258 #259 #257

**Comment by aandrew-me** [comment]
I appreciate you pointing out those issues
