### ISSUE TITLE
[BUG] The download complete popup doesn’t redirect me to the folder where the video is saved

### ISSUE THREAD

**Issue by memebl14** [aandrew-me/ytDownloader#258]
The download complete popup doesn’t redirect me to the folder where the video is saved

This **only** happens when I use the function to download part of the video

![image](https://github.com/user-attachments/assets/2abf03e0-76c0-46a3-bac9-746dcefd74de)

When the app notifies that the download is complete, clicking the popup notification doesn’t do anything.

![image](https://github.com/user-attachments/assets/c218da8f-42e6-45d6-813b-2f99fd7615aa)

**To Reproduce**
1.  Try to download any youtube video (like https://www.youtube.com/watch?v=SDTZ7iX4vTQ )
2. Set a particular time-range to download
3. Wait for the download to finish, then try clicking on the notification

**Info (please complete the following information):**
 - Operating system: Windows 10
 - App version: 3.18.3.0
 - Package version (flatpak/snap/other): YTDownloader_Win.exe

------------

To be clear, this only happens if you use the function to download only part of the video

**Comment by memebl14** [comment]
Hello, this problem persists in the latest update :(

**Comment by aandrew-me** [comment]
Are you sure? I tested with the video link you provided and it worked fine for me. Provide exact steps to reproduce the issue

**Comment by memebl14** [comment]
I recorded a gif to show you
![ytdownloader 4](https://github.com/user-attachments/assets/036162b7-ea5c-4b09-930d-a63a59e286c8)



Also, clicking on “Saved file. Click to open” does not work on videos downloaded using the Download Section feature

it works normally when downloading the full video, the only reason I can think of is that my windows is in portuguese and not in english

**Comment by aandrew-me** [comment]
All good on your side, there is still an issue left, thats why

**Comment by memebl14** [comment]
will this be fixed in the next update?

**Comment by aandrew-me** [comment]
Yes
