### ISSUE TITLE
[BUG] Trojan Virus "Wacatac.B!ml"

### ISSUE THREAD

**Issue by Tod902** [aandrew-me/ytDownloader#262]
**Bug Description**
After starting the app, it's says downloading necessary files. I would guess that this is just an auto-update being done. The thing is that it's seems to try and download a trojan virus. At least my Windows Defender says so. Windows Defender quarantines the trojan and if I start the app again it tries to redownload it.

What I find strange is that it's only happening now or rather since today. And the app is multiple versions behind if I am not mistaken, so why is it doing what I assume is an auto-update now? 

I also downloaded a video from a somewhat sketch website before hand, but it wasn't the first time and it doesn't make sense to me that it would effect the ytDownloader app itself.

Furthermore, I've now uninstalled the app because of tha above.

**To Reproduce**
1. Version 3.15.0 (I think), auto update

**Screenshots**
![IMG_20241110_152120](https://github.com/user-attachments/assets/492289a2-30f5-425a-a6b4-aefc5eb8894e)

**Info (please complete the following information):**
 - Operating system: Windows 10
 - App version: 3.15
 - Package version (flatpak/snap/other): None, downloaded it via Zip a few Versions ago. I think it was 3.11

**Comment by aandrew-me** [comment]
Its downloading yt-dlp - https://github.com/yt-dlp/yt-dlp/releases

I don't know why defender is screaming, maybe try using the latest version

**Comment by Tod902** [comment]
Thanks for the info. 
I just tried it and it also happens when using the latest version 3.18.4 
![image](https://github.com/user-attachments/assets/c03a26f2-7e95-45e8-9d9f-5387dd19a86d)

**Comment by aandrew-me** [comment]
I tested the file and didn't see any issues - https://www.virustotal.com/gui/file/504dbcb3cb6ba2e9207a79c1010d9a7663e74de674ee6983a5c72642698c1ad5

So the only option I see for you is to allow it from **Actions**, you can then manually upload the file to virustotal to confirm that its safe

**Comment by aandrew-me** [comment]
Windows Defender often gives false positives

**Comment by Tod902** [comment]
I uploaded it to virustotal and it automatically sent me to the link you sent, meaning that it's the same file. As you have might already seen the only issue virustotal detects is that it is flagged as malicious by W64.AIDetectMalware according to Bkav Pro. As you suggestedy Windows Defender seems to have given a false positive.
Thank you for spending your time on this issue :)

**Comment by aandrew-me** [comment]
Wish you a wonderful day/night :)
