### ISSUE TITLE
[BUG] Playlist mode downloads all videos in 360p, despite preferences

### ISSUE THREAD

**Issue by FredsMedia** [aandrew-me/ytDownloader#263]
**Bug Description**
When i download a playlist of videos, all in 1080p and my preferences set to 1080p, it downloaded all 21 videos in 360p.

**To Reproduce**
1. Select playlist mode
2. Set resolution preference
3. Copy playlist link
4. Videos are in 360p

**Screenshots**
<img width="950" alt="Screenshot 2024-11-11 at 10 07 02 am" src="https://github.com/user-attachments/assets/2afdfcdc-0d04-4e1e-b78e-97712f13e4fe">
<img width="512" alt="Screenshot 2024-11-11 at 10 07 31 am" src="https://github.com/user-attachments/assets/21489255-c5b9-4051-b92d-3b96fedaf978">

**Info (please complete the following information):**
 - Operating system: MacOS
 - App version: 3.18.3
 - Package version (flatpak/snap/other): other

**Comment by aandrew-me** [comment]
Can you send the playlist link. 
And was it set to 1080p before downloading?
![image](https://github.com/user-attachments/assets/0ff82f4b-ad04-4a1f-ba48-3f9e118f571d)

**Comment by FredsMedia** [comment]
Yes, it was set to 1080p before downloading. [Link to playlist](https://m.youtube.com/playlist?list=PLAF9YEj--eyhOBfBI1LD92CoYoR6EZYP-)

**Comment by aandrew-me** [comment]
![image](https://github.com/user-attachments/assets/d5bb0ba4-0228-4712-8dd3-cc07f5214ed5)

It worked fine for me. So either its some network related issue where you are being rate limited, or it is some mac os related issue.

**Comment by FredsMedia** [comment]
Maybe. I have tried on multiple networks and it persists so I don’t think it would be a network related issue. Let me try on Fedora real quick

**Comment by FredsMedia** [comment]
I think i know what is going on. If I set the preference to mp4, it will download at 360p. However, if i put it on auto (which downloads as mkv files) or as webp, it downloads at 1080p.

**Comment by aandrew-me** [comment]
I will take a look, thanks

**Comment by aandrew-me** [comment]
Should be fine now
