### ISSUE TITLE
[Feature Request] use `vedantmgoyal9/winget-releaser` action to automatically release new versions to winget

### ISSUE THREAD

**Issue by soredake** [aandrew-me/ytDownloader#264]
**Description**
Use [vedantmgoyal9/winget-releaser](https://github.com/vedantmgoyal9/winget-releaser) action to automatically release new versions to winget.

Example https://github.com/topgrade-rs/topgrade/blob/main/.github/workflows/release_to_winget.yml

**Comment by aandrew-me** [comment]
Where do I get the winget token?

**Comment by soredake** [comment]
> And I don't maintain the winget package

You don't need to maintain it, github action will do this for you.

>Where do I get the winget token?

It's all in the instructions:
![изображение](https://github.com/user-attachments/assets/5d7b422d-5a8d-49bc-9b22-0d217584ef78)

**Comment by aandrew-me** [comment]
Right right, thanks
