### ISSUE TITLE
[BUG] ERROR: [twitter] 1857447128827658331: 1857447128827658331: 

### ISSUE THREAD

**Issue by serial02** [aandrew-me/ytDownloader#265]
Hello Video Downloader Team

Can you check this error message that is constantly happening when trying to download videos from X (Old Twitter)?

```

		URL: https://twitter.com/i/status/1857447128827658331
		
		ERROR: [twitter] 1857447128827658331: 1857447128827658331: Failed to parse JSON (caused by JSONDecodeError("Expecting value in '': line 1 column 1 (char 0)")); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**To Reproduce**
1. Normal and standard procedure to download any video via the URL of any website through the application.

**Screenshots**

![Captura de tela de 2024-11-15 13-51-40](https://github.com/user-attachments/assets/c3842dd0-f9f9-41d4-832a-81bb72625d05)

**Info (please complete the following information):**
 - Operating system: Linux Fedora 41 com Wayland
 - App version: 3.18.4 ( https://github.com/aandrew-me/ytDownloader/releases/tag/v3.18.4 ).
 - Package version (flatpak/snap/other): Installed manually: : ( https://github.com/aandrew-me/ytDownloader/releases/download/v3.18.4/YTDownloader_Linux.rpm )

**Comment by aandrew-me** [comment]
It looks like some kind of network issue. I tried and it worked fine for me. Try with a VPN or proxy or some other way
![image](https://github.com/user-attachments/assets/dc51f77a-833d-4a86-96ba-ee3d1b0a3061)
