### ISSUE TITLE
[BUG] Install package swapped MacOS ARM <=> x64

### ISSUE THREAD

**Issue by RayOei** [aandrew-me/ytDownloader#267]
The provided packages for MacOS are switched. 
The ` YTDownloader_Mac_arm64.dmg` doesn't work on ARM but the ` YTDownloader_Mac_x64.dmg` does. So it seems the names are switched. This is true for the `dmg` package as well as the `zip`.
 
Reproduce**
1. Download `arm64` version on Mac M2 
2. Install in Applications
3. Start
4. Error: `YTDownloader.app” is damaged and can’t be opened. You should move it to the Bin.`
5. Download `x64` version
6. Install
7. Start => application starts without issues

- Operating system: Sonoma 14.7
 - App version: 3.18.4

**Comment by aandrew-me** [comment]
The builds are automated, so packages switching doesn't sound possible. People have encountered issues on arm mac - https://github.com/aandrew-me/ytDownloader/issues/240
Try the solution

**Comment by RayOei** [comment]
@aandrew-me Thanks! I never knew MacOS is apparently able to run x64 apps too on Apple silicon. That confused me. Either way, thanks again.
