### ISSUE TITLE
[BUG] Unable to find other folder options to save videos in the home folder

### ISSUE THREAD

**Issue by serial02** [aandrew-me/ytDownloader#268]
**Bug Description**
Unable to find other folder options to save videos in the home folder

**To Reproduce**
1. /home/edson/Downloads/YTDownloader

**Screenshots**

![Captura de tela de 2024-11-17 23-51-06](https://github.com/user-attachments/assets/2c5e5497-e53e-484c-b4ae-2165a976bf99)

**Info (please complete the following information):**
 - Operating system: Arch Linux com Gnome 47
 - App version: 3.18.4
 - Package version (flatpak/snap/other): flatpak ( flatpak install flathub io.github.aandrew_me.ytdn )

**Comment by aandrew-me** [comment]
I couldn't understand your issue

**Comment by aandrew-me** [comment]
Well its the native file picker popup. It has nothing to do with ytDownloader. 
You can choose other locations like this-
[e.png](https://github.com/user-attachments/assets/9c7daafb-8fc6-46af-8147-4b928e04e544)

**Comment by serial02** [comment]
> Well its the native file picker popup. It has nothing to do with ytDownloader. You can choose other locations like this- [Screenshot.png](https://github.com/user-attachments/assets/9c7daafb-8fc6-46af-8147-4b928e04e544)

That's exactly it! Once the application is opened on my Arch Gnome, the other folders do not appear in the selector to be changed. Only the downloads folder appears in the home page. Did you understand? The other folders should appear, namely: Video, Music and Documents, correct?

**Comment by aandrew-me** [comment]
Well its the native file picker popup. It has nothing to do with ytDownloader. 
You can choose other locations like this-
[e.png](https://github.com/user-attachments/assets/9c7daafb-8fc6-46af-8147-4b928e04e544)

    Ah yes, its most likely because youre using flatpak, so the app only has access to Downloads directory. You can add access to more folders with flathub

**Comment by aandrew-me** [comment]
Ah yes, its most likely because youre using flatpak, so the app only has access to Downloads directory. You can add access to more folders with flathub

**Comment by serial02** [comment]
> flatseal
And how is this added?

**Comment by aandrew-me** [comment]
https://flathub.org/apps/com.github.tchx84.Flatseal
