### ISSUE TITLE
FFmpeg nonfree

### ISSUE THREAD

**Issue by trimechee** [aandrew-me/ytDownloader#270]
Hi, i found a "nonfree" ffmpeg that seems to overcome some of the limitations of the official classic ffmpeg.....maybe be it can help the project :::

Automated nonfree builds of FFmpeg for Windows using GitHub Actions:

https://github.com/AnimMouse/ffmpeg-autobuild
https://www.animmouse.com/projects/ffmpeg-autobuild/

other builds of FFmpeg built by others :

https://www.animmouse.com/p/ffmpeg-binaries/

**Comment by aandrew-me** [comment]
I appreciate that, however I am already using a custom ffmpeg build made by yt-dlp
