### ISSUE TITLE
[BUG] `Failed to execute script '__main__' due to unhandled exception!` error with any URL

### ISSUE THREAD

**Issue by soredake** [aandrew-me/ytDownloader#272]
**Bug Description**
I get `Failed to execute script '__main__' due to unhandled exception!` error with any URL

**To Reproduce**
1. Download latest version.
2. Launch it.
3. Try to download `https://www.youtube.com/watch?v=nrmH8uhzMa4` for example.
4. `Failed to execute script '__main__' due to unhandled exception!`

**Screenshots**
![изображение](https://github.com/user-attachments/assets/c894beb5-6ccc-4adc-a1b2-19e6ab094e05)

**Info (please complete the following information):**
 - Operating system: Windows 11 Pro
 - App version: 3.18.4
 - Package version (flatpak/snap/other): 3.18.4

**Comment by aandrew-me** [comment]
![image](https://github.com/user-attachments/assets/57dcec3a-6c9f-4402-911b-88a438d38e30)
Windows 11 Pro, working fine

Try reinstalling

**Comment by soredake** [comment]
![изображение](https://github.com/user-attachments/assets/8e6d805e-c222-4e0a-9999-dbdc3687e95a)

After clearing ytdownloader settings, I get this error.

**Comment by aandrew-me** [comment]
Youre not pasting a url
