### ISSUE TITLE
German translation

### ISSUE THREAD

**Issue by Proxycon** [aandrew-me/ytDownloader#35]
Hi, I would love to provide a German translation.
If you could add the language to Crowdin I could start translating right away,

**Comment by aandrew-me** [comment]
Great!

I have added it.

**Comment by Proxycon** [comment]
Done. Thanks for the quick response!

**Comment by aandrew-me** [comment]
Thank you for your work! What do German people call German language (in their own language)?

**Comment by Proxycon** [comment]
Deutsch

**Comment by aandrew-me** [comment]
Thank you. 'Deutsch' will be there in the next update and I am putting your name beside German in README.
