### ISSUE TITLE
cant download :))

### ISSUE THREAD

**Issue by cubinz** [aandrew-me/ytDownloader#4]
![2022-8-29 17-55-44](https://user-images.githubusercontent.com/111338817/187175725-22ceff20-6566-46fe-9afd-181cbb6a319c.jpg)

**Comment by aandrew-me** [comment]
Hello.

Can you provide more details. Like which URL you were using

**Comment by aandrew-me** [comment]
I found that things are not working properly in Windows. I am trying to fix it ASAP.

**Comment by aandrew-me** [comment]
Hey!

There issue should not be there in the latest release. Please let me know if you can.

**Comment by cubinz** [comment]
working ^^!

**Comment by cubinz** [comment]
`rangeCmd` thanks!
