### ISSUE TITLE
"Some error has occured" for certain videos

### ISSUE THREAD

**Issue by blurredbeeble** [aandrew-me/ytDownloader#44]
I've tried downloading a variety of videos with ytDownloader (using the flatpak version on Linux) and most of them seem to work fine. However when trying to download videos from this channel https://www.youtube.com/c/justkethVOD almost all videos seem to throw the error 'Some error has occurred. Check your network and use correct URL'
Initially I thought that might have to do with the file size of the videos, as they are quite long. But other equally long videos from other channels seem to work just fine. So I'm curious to see if this error can be replicated by other people (using this video for example https://www.youtube.com/watch?v=UUnK0h3YZCg ) and what exactly is behind the error.

**Comment by aandrew-me** [comment]
Interesting. Thanks for reporting this. I am taking a look at it...

**Comment by aandrew-me** [comment]
I have identified and fixed the problem. It should gone in the next update

**Comment by aandrew-me** [comment]
The issue has been fixed. It would be great if you can confirm it :)

**Comment by blurredbeeble** [comment]
It works now. That was very quick. Thank you very much!

**Comment by blurredbeeble** [comment]
It works now. That was very fast. Thank you very much!
