### ISSUE TITLE
Links from playlist download wrong audio when using "extract"

### ISSUE THREAD

**Issue by imbev** [aandrew-me/ytDownloader#45]
When copying a youtube video url from a playlist (https://youtu.be/NSlkW1fFkyo?list=PLmOldskd2VbL7_t-NE9p6rEboq_v0AHko), the app downloads the wrong video.

**Comment by aandrew-me** [comment]
I tried downloading the video from the link that you have provided and it downloaded the correct one.
![image](https://user-images.githubusercontent.com/66430340/191655491-fb4c6e7a-34c5-4711-be3b-0bc29f8cee7f.png)

So can you please provide more details. Like which version of the app you are using, which variant of the app you are using (appimage/flatpak/snap/deb) and which video was actually downloaded?

**Comment by imbev** [comment]
The metadata was correct, but the audio was of the first video of the playlist, not the correct one.

I just tested it, and it works as it should when using "download", but the problem occurs when using "extract" audio.

3.5.1 Flatpak

**Comment by aandrew-me** [comment]
Thanks for clarifying. There is indeed an issue and it will be gone in the next update.

**Comment by aandrew-me** [comment]
It would be great if you can confirm that it has been fixed. Also that's some nice Music!

**Comment by imbev** [comment]
The problem is now fixed with the new update. Thanks, I think so too.
