### ISSUE TITLE
Some error has occurred

### ISSUE THREAD

**Issue by FlyinPancake** [aandrew-me/ytDownloader#5]
Hi I ran into this problem

![image](https://user-images.githubusercontent.com/36113055/187272463-fd6504bd-256e-442d-944e-240ba052344e.png)

I tried both appimage and flatpak and it's the same problem

This is the video i'd like to download: https://www.youtube.com/watch?v=8x1w8UbW2Ps

**Comment by FlyinPancake** [comment]
Sorry I messed up the link: https://youtu.be/sRLAwvq4qhA

**Comment by aandrew-me** [comment]
Hello!
Thank you for reporting the problem. Also I really appreciate the console logs.

I tried to download the video and it downloaded without problems.


Is yt-dlp already installed?  If installed, please test this command
```
sh -c 'yt-dlp -f "278+ba" -o output.webm "https://youtu.be/sRLAwvq4qhA"'
```

**Comment by aandrew-me** [comment]
Several things have been fixed after your issue. If you still have problems, open the issue again. I am closing it for now.
