### ISSUE TITLE
YTDownloader-3.6.2 -deb package

### ISSUE THREAD

**Issue by chris2553** [aandrew-me/ytDownloader#54]
Have you stopped producing .deb packages or is it's absence for release 3.6.2 just an error?

**Comment by aandrew-me** [comment]
I have stopped producing. Lack of updating is the primary reason. But if you need, I can bring it back

**Comment by chris2553** [comment]
I actually use rpm to manage packages on my system which is built using the Linux From Scratch recipes. Creating a binary rpm from a .deb.file is very easy, so the YTDownloader.deb package has been useful. I'll have a go at building one from the source tarball and get back if I have problems with that process.

**Comment by aandrew-me** [comment]
No problem man, I am publishing rpm package.

**Comment by chris2553** [comment]
Wow, that's great thanks. And thanks for your work on YTDownloader.

**Comment by chris2553** [comment]
The rpm is working fine, thanks.
