### ISSUE TITLE
Brazilian Portuguese translation

### ISSUE THREAD

**Issue by andre1828** [aandrew-me/ytDownloader#56]
Hi,

I would like to contribute with a Brazilian Portuguese 🇧🇷   translation!

**Comment by aandrew-me** [comment]
Hey!

Thanks, that's great! I have added Brazilian Portuguese (pt-Br). You can now start contributing.

**Comment by andre1828** [comment]
Translations are done. I appreciate the opportunity to contribute 🤝 .

**Comment by aandrew-me** [comment]
Thank you very much for your contribution!

**Comment by aandrew-me** [comment]
What do you people call your language?
