### ISSUE TITLE
[feature request] download audio playlist.

### ISSUE THREAD

**Issue by splace** [aandrew-me/ytDownloader#59]
![image](https://user-images.githubusercontent.com/1234848/198338670-d6d70978-b0b6-4855-9383-83068b1334dc.png)

**Comment by aandrew-me** [comment]
That option is still not there. I will add it when I get time :)

**Comment by aandrew-me** [comment]
The feature has been added to the source code and will be available in next update.

**Comment by splace** [comment]
today; i got a update notification from flathub, nice.

**Comment by splace** [comment]
couple of things...

using this playlist  https://www.youtube.com/watch?v=If_ilVsVepU&list=PLsY30fLfDNuLjne8S--lFF4wVnoqieoW1

all was great, until...

![image](https://user-images.githubusercontent.com/1234848/199276989-95d7e27a-b5ba-4497-af2e-da68779bd494.png)

it seems to be trying to get one more than exists...

![image](https://user-images.githubusercontent.com/1234848/199277460-e9e63d88-970a-47eb-8bbf-c69586f583a0.png)

**Comment by aandrew-me** [comment]
Could you please provide more details on what happened?

**Comment by splace** [comment]
also...

106 is labelled 107, with the last 5 labelled 1 out.

![image](https://user-images.githubusercontent.com/1234848/199278183-ed3ae9ae-01e7-42ef-a6d9-ba08564d276b.png)

**Comment by splace** [comment]
and i clicked m4a but got webm containing opus

**Comment by aandrew-me** [comment]
Okay I see thanks. One thing I found out is that after the playlist download is complete, then the error message shows up even though everything downloaded properly. I will fix it. And I am looking into this too

**Comment by splace** [comment]
sorry, i might be trying to use the 'wrong' tool here; this particular playlist is functioning as a podcast, being added too continuously, and so downloading needs to skip already downloaded.

**Comment by aandrew-me** [comment]
It would skip the already downloaded files. But the problem is every time you download a playlist, some random characters are there in the name to make it unique. The app is using yt-dlp and sometimes the playlist name is not there. I will try to find a solution and fix it. (Maybe by using the hashsum of the url)

**Comment by aandrew-me** [comment]
I figured out the reason for errors when downloading audios. So it will be fixed soon.

**Comment by splace** [comment]
> It would skip the already downloaded files. But the problem is every time you download a playlist, some random characters are there in the name to make it unique.

i see, i did notice, and didn't understand why, the download page showed the playlist's name, but the folder they were saved into doesn't just use it.

**Comment by aandrew-me** [comment]
There are no more problems. Everything will be solved. The folder names can either be playlist names or playlist IDs. I want to use playlist IDs since they are unique as different playlists may have same folder name. Do you have any suggestions?

**Comment by splace** [comment]
> Do you have any suggestions?

i've seen name with UUID appended before, people have got used to seeing non-human readable stuff on the end of file names etc.

**Comment by splace** [comment]
> I have pushed an update to flathub. It will soon be available. Please let me know if you face any problems.

downloaded a large audio playlist, no issues.

**Comment by aandrew-me** [comment]
Thank you!
