### ISSUE TITLE
[Feature Request] Download multiple videos at once and be able to trim videos after downloading

### ISSUE THREAD

**Issue by Terkyz** [aandrew-me/ytDownloader#6]
Basically that, put several links in a row and download several videos in a row and be able to cut videos once downloaded

**Comment by aandrew-me** [comment]
Thanks for your request. I will implement these features.

**Comment by aandrew-me** [comment]
I assume you meant 2 separate features 
1. Support for downloading multiple videos
2. Ability to specify time ranges when downloading videos.

In that case, 2nd feature has been added and 1st one is pending.

**Comment by aandrew-me** [comment]
Sadly its not possible. And what the app is doing is not trimming the video but downloading that particular specified range. I think its more convenient to use a video editor to trim it.
