### ISSUE TITLE
[Feature Request] Active downloads limit / queue

### ISSUE THREAD

**Issue by MrQuerter** [aandrew-me/ytDownloader#65]
Hope you don't mind few feature suggestions.

Basically what active downloads limit would allow is to well, limit the number of active downloads. Usually downloads finish faster when it's file by file and not many of them at once. With that limit you wouldn't need to wait for a file to finish to add a new one, but just add it to the list and it would begin automatically when previous download finishes.

**Comment by aandrew-me** [comment]
Suggestions are always welcomed.
That is a very good suggestion. I will surely try to implement it.

**Comment by aandrew-me** [comment]
> > Hope you don't mind few feature suggestions.
> > Basically what active downloads limit would allow is to well, limit the number of active downloads. Usually downloads finish faster when it's file by file and not many of them at once. With that limit you wouldn't need to wait for a file to finish to add a new one, but just add it to the list and it would begin automatically when previous download finishes.
> 
> and i need mobile app +1 :D

There is a good youtube client for android - [Newpipe](https://newpipe.net/)
