### ISSUE TITLE
[Feature Request] Remember chosen resolution

### ISSUE THREAD

**Issue by MrQuerter** [aandrew-me/ytDownloader#66]
Okay, last suggestion for today.

Some kind of setting that would remember the preferred resolution so you don't have to select it yourself every time.

One thing that could complicate it is the fact that some resolutions can have multiple file sizes even though the file type (and well, the resolution) is the same.

If a chosen resolution isn't available it goes down 1 lvl. For example - You set "720p (highest size) mp4", but it's not available so it tries the "480p (highest size) mp4".

I have no idea if it's even possible to do it here, but when I was using 4k video downloaded few years ago it was a really good option.

**Comment by aandrew-me** [comment]
I don't think it will be hard. I will add all of these features once I get the time.

**Comment by aandrew-me** [comment]
Feature has been added to source code. ✅
