### ISSUE TITLE
Translation Contribution – Farsi/Persian

### ISSUE THREAD

**Issue by TheBlueQuasar** [aandrew-me/ytDownloader#67]
Hello there,
I would like to contribute to the translation of the app for Persian/Farsi language. Add it to the Crowdin page of the project if you may, and I'll start working on that.

**Comment by aandrew-me** [comment]
Hey!
I have added Persian language. I really appreciate that!
Considering the fact that Persian is written from right to left, I wonder how it will look like in the app!

**Comment by aandrew-me** [comment]
Thanks for translating!
Do things look in order?
![image](https://user-images.githubusercontent.com/66430340/201137597-90e49c6e-6021-4606-835c-55a92bff2af4.png)
![image](https://user-images.githubusercontent.com/66430340/201137563-0ed0e8b4-5e1f-4269-bc04-9359e8fafc46.png)

**Comment by TheBlueQuasar** [comment]
All done. Yes I noticed this is the first right-to-left language translation of the app. The Crowdin did throw some kind of error about the question marks, but they are correct in Persian/Farsi the way I typed.
The Persian-translated screenshots you posted are all good. It may have been just a little better looking if the text on the preferences page were aligned from right, but I assume that can't be done without messing with the app code. And it looks absolutely fine as in this screenshot in my opinion.

**Comment by TheBlueQuasar** [comment]
@aandrew-me Glad to contribute something to the app. It's very well in every aspect, and excellently maintained. Thank you for providing it!

**Comment by aandrew-me** [comment]
Thank you very very much! You're right, alignment in preference will require change in source code. However I will try to do it.

**Comment by aandrew-me** [comment]
> @aandrew-me Glad to contribute something to the app. It's very well in every aspect, and excellently maintained. Thank you for providing it!

Thank you! It means a lot!

**Comment by aandrew-me** [comment]
I am closing the issue
