### ISSUE TITLE
[Bug] Invalid start time for chapter

### ISSUE THREAD

**Issue by MrQuerter** [aandrew-me/ytDownloader#69]
I noticed this on few videos, but it's kind of rare.

When you click on the button it loads for a while and throws in-app error in red text:
>Some error has occured. Check your network and use correct URL

When you go to dev tools (seriously, it's great that you didn't hide them) it shows this output:
>WARNING: [youtube] Invalid start time (1080.0 < 0) for chapter "OPEN 17:30 / START"
renderer.js:231

I'm only submitting this bug report, because when you use yt-dlp it works without problems.
 
Here's such an example where it happens, maybe you can identify what's wrong: https://www.youtube.com/watch?v=40wCYyxpmnI

**Comment by aandrew-me** [comment]
That's very interesting. I have never seen such a problem before. Let me see..

**Comment by aandrew-me** [comment]
No big deal!  yt-dlp was throwing a warning, but it was being counted as an error.

**Comment by MrQuerter** [comment]
Tested the patch and can confirm it works now.

By the way, would you want a new translation, but posted in issues here as .txt file? I don't want to fork ytdownloader or create any new accounts, but I could localize it, upload it here and you can do what you want with it.

**Comment by aandrew-me** [comment]
Sure!
Take the en.json file
https://github.com/aandrew-me/ytDownloader/blob/main/translations/en.json
and replace the values on the right with the right words in the desired language.
