### ISSUE TITLE
Can't find a way to translate ytDownloader to other languages?

### ISSUE THREAD

**Issue by heidiwenger** [aandrew-me/ytDownloader#7]
About 95% of the world don't speak English as a first language, and 75% don't speak English at all, so these things, i think, are important.

Many projects use Weblate (which can be self hosted), Crowdin, Transifex or Launchpad. These are the most simplest ways to do it for everyone too. Thanks.

**Comment by aandrew-me** [comment]
I really appreciate your post. I completely agree with you.

I will try to make translating possible. Thanks!

**Comment by heidiwenger** [comment]
> Hello!
> 
> I have already started working on implementing translations. If you want to translate to any language, let me know! And of-course a translator's username will be there for their contribution.

I want to translate.

**Comment by aandrew-me** [comment]
That's great. I have integrated Crowdin with this project. I am still new to this, please consider that.

What language do you want to translate to?

**Comment by KotoWhiskas** [comment]
> That's great. I have integrated Crowdin with this project. I am still new to this, please consider that.
> 
> What language do you want to translate to?

Hey, I'm not that guy but I would also like to translate it, to Ukrainian

**Comment by aandrew-me** [comment]
> 

Great! I will send invitation link once everything is properly setup.

**Comment by heidiwenger** [comment]
> That's great. I have integrated Crowdin with this project. I am still new to this, please consider that.
> 
> What language do you want to translate to?

Finnish. So can i join the Crowdin instance, then? What is the link? Thanks.

**Comment by aandrew-me** [comment]
Sure you can. 

Here you go - https://crwd.in/ytdownloader

**Comment by aandrew-me** [comment]
I am closing this. I will add more translation related info to README. Thanks guys!
