### ISSUE TITLE
Preffered format can change

### ISSUE THREAD

**Issue by MrQuerter** [aandrew-me/ytDownloader#74]
Hi.
I've seen that it now automatically remembers the format that you pick. Would prefer to set it manually, but that's ok.
However one annoyance I have found (not exactly a bug, and not a feature) is that when for example you download something as 720p and the next file you download has only 480p, then 480p is set for next download after that even if 720p is available.

**Comment by aandrew-me** [comment]
Okay I will add 'Preferred Video quality' and 'Preferred audio quality' options to Preferences
