### ISSUE TITLE
Full name of the playlist uploader and Name of the playlist that contains the video

### ISSUE THREAD

**Issue by candrapersada** [aandrew-me/ytDownloader#76]
will there be Full name of the playlist uploader and Name of the playlist that contains the video in the playlist like
`'%(uploader)s/%(playlist)s/%(playlist_index)s- %(title)s.%(ext)s'`

**Comment by candrapersada** [comment]
and is it possible to use the [config.txt file](https://github.com/yt-dlp/yt-dlp#configuration) so that you can use other arguments from yt-dlp

**Comment by aandrew-me** [comment]
> will there be Full name of the playlist uploader and Name of the playlist that contains the video in the playlist like `'%(uploader)s/%(playlist)s/%(playlist_index)s- %(title)s.%(ext)s'`

When downloading a playlist with `%(uploader)s/` then if that playlist contains videos from different channels, then several different folders will get created. So using playlist name seems a better option

**Comment by aandrew-me** [comment]
Changes will be made according to #81

**Comment by candrapersada** [comment]
Why is my problem closed before the `config.txt` problem is finished?

**Comment by aandrew-me** [comment]
I have created a new issue regarding config.txt file
