### ISSUE TITLE
Not working, error occur

### ISSUE THREAD

**Issue by spidy2356** [aandrew-me/ytDownloader#8]
![Screenshot (5)](https://user-images.githubusercontent.com/101243689/187965184-4c5da9cb-4e33-4f70-824a-aa6baac29880.png)

**Comment by aandrew-me** [comment]
Hello!

Thanks for reporting. If you put your mouse cursor on - "Some error has occured. Hover to see details". It will show a message. Can you please send the screenshot of it?

**Comment by aandrew-me** [comment]
I have found the problem. It's a path related problem, unique to windows. I will fix it ASAP and release a new update.

**Comment by spidy2356** [comment]
> I have found the problem. It's a path related problem, unique to windows. I will fix it ASAP and release a new update.

![IMG_20220901_232523](https://user-images.githubusercontent.com/101243689/187982371-fe73494e-89b8-41df-8c8b-45c282829ad6.jpg)
![IMG_20220901_232523](https://user-images.githubusercontent.com/101243689/187982125-63db54b3-7681-4624-8709-b4c467909c71.jpg)

**Comment by aandrew-me** [comment]
I have published a new update. It should be fixed. Please let me know
