### ISSUE TITLE
[Feature Request] Select a range of videos to download in a playlist

### ISSUE THREAD

**Issue by Nikko-A** [aandrew-me/ytDownloader#80]
Hello!

I have a playlist that I frequently update with video resources and audio while downloading. Problem is that this becomes problematic when I need to frequently update it, either wastes time checking hundreds of downloads or constantly crawls youtube's site. Since Youtube_DL supports downloading a specific range, I was wondering if that could also be implemented as an advanced option?

I had a different idea but I'm not sure if it would be possible. Considering how videos within playlists usually have an index attached to them at the end, would it be possible to begin a download using the specific index a video and then continue downloading the playlist onward automatically?

**Comment by aandrew-me** [comment]
Hey!
I really appreciate you giving some important feature ideas.

There is an argument in yt-dlp which is
```
-I, --playlist-items ITEM_SPEC  Comma separated playlist_index of the videos
                                to download. You can specify a range using
                                "[START]:[STOP][:STEP]". For backward
                                compatibility, START-STOP is also supported.
                                Use negative indices to count from the right
                                and negative STEP to download in reverse
                                order. E.g. "-I 1:3,7,-5::2" used on a
                                playlist of size 15 will download the videos
                                at index 1,2,3,7,11,13,15
```

Is this what you are referring to?

**Comment by Nikko-A** [comment]
Yup! That was exactly what I wanted to pitch!

**Comment by aandrew-me** [comment]
Great then! I will add all the requested features once I get the time.
