### ISSUE TITLE
[Feature Request] Ability to create own naming system for downloaded videos

### ISSUE THREAD

**Issue by Nikko-A** [aandrew-me/ytDownloader#81]
Hello Again!

I really appreciate that videos from playlists are properly labeled. However, I frequently update a playlist I have and I needed the video titles to be consistent and considering how often videos can be removed off of playlists, that consistency could very much get ruined. I wanted to know if there could be a way to implement our own naming scheme for files, like removing the present labelling system or creating our own naming scheme, to allow a more flexible workflow. 

ShareX does something like this:
![image](https://user-images.githubusercontent.com/74495189/202906426-1e2cf9d6-e923-4daf-82ee-2af810bc7ee0.png)

**Comment by aandrew-me** [comment]
That's definitely a good idea. This feature can surely be added where there will be a naming format for playlist downloads in app preferences. The yt-dlp [output templates](https://github.com/yt-dlp/yt-dlp#output-template) would then be available for use added with the ability to use own words too.

Examples
`%(upload_date>%Y)s/%(title)s.%(ext)s`
`%(uploader)s/%(playlist)s/%(playlist_index)s - %(title)s.%(ext)s`

I hope this is what you meant?

**Comment by Nikko-A** [comment]
That is exactly what I meant. Thank you for considering this!

**Comment by aandrew-me** [comment]
Options have been added to the code. They will be available in next update

![image](https://user-images.githubusercontent.com/66430340/203954351-effb9623-7f35-46e1-a51d-47cfc58e01ca.png)
