### ISSUE TITLE
[Feature Request] Playlist backup?

### ISSUE THREAD

**Issue by MrQuerter** [aandrew-me/ytDownloader#82]
Just a wild suggestion, don't know if it's worth to add it, but it doesn't sound impossible.

I have a playlist on YouTube that I would want to save in some way, but I don't want to download all of the videos there.

Would it be possible to have an option to save just the links and thumbnails of the playlist where every image would have a title from YouTube and the watch ID?

example:
You paste a playlist with 3 videos
It makes 3 files with (title)_(id).png and possibly a txt file with just the links to the videos.

**Comment by aandrew-me** [comment]
Haha both are possible. But how much practical is it to add such features?

And here is how you can do that with yt-dlp
- For downloading just thumbnails
```
yt-dlp --yes-playlist --write-thumbnail --convert-thumbnails png --skip-download -o "%(title)s_%(id)s.%(ext)s" "playlist_url_here"
```
- For creating a file with just links to videos
```
yt-dlp --yes-playlist --write-thumbnail --convert-thumbnails png --skip-download -o "%(title)s_%(id)s.%(ext)s" "playlist_url_here"
```

**Comment by MrQuerter** [comment]
Probably practical just for my use case.

I add videos to watch later list, they are often deleted before I can watch them and YouTube doesn't even show the thumbnail or title of the video so I don't know what I missed. This would help to find out since it would keep the thumbnail and title so you could compare it.

Also, I think you have pasted the same command twice. Still, thank you for that.

**Comment by aandrew-me** [comment]
Thy wisheth hast been fulfilled. They will be available in the next update

**Comment by candrapersada** [comment]
how to use links.txt File containing URLs to download on ytDownloader?

**Comment by aandrew-me** [comment]
> how to use links.txt File containing URLs to download on ytDownloader?

Just do `yt-dlp -a links.txt`

**Comment by candrapersada** [comment]
add option Embed thumbnail in the audio as cover art
`--embed-thumbnail`

**Comment by aandrew-me** [comment]
> add option Embed thumbnail in the audio as cover art `--embed-thumbnail`

Embedding thumbnail requires `ffprobe`. I already have to include ffmpeg binary with the app which increases the app size a lot. So I don't want to include `ffprobe` binary
