### ISSUE TITLE
[Feature Request] config.txt file

### ISSUE THREAD

**Issue by aandrew-me** [aandrew-me/ytDownloader#83]
Check if it is possible to use config.txt file

**Comment by aandrew-me** [comment]
[candrapersada](https://github.com/candrapersada)

**Comment by aandrew-me** [comment]
Its possible to use a config file. I will try to add an option to use config file in App **Preferences**

**Comment by candrapersada** [comment]
![aa3](https://user-images.githubusercontent.com/36833664/203475798-e471f5a6-d4d1-4967-8ec6-dfccb4a2b0c0.PNG)

**Comment by aandrew-me** [comment]
I am afraid it's not. Video and audio quality can already be selected when downloading videos. For some additional options, there will be an option to choose a config file in preferences. But if there are conflicts between config file and options selected in the app, most likely the one selected in the app will override them

**Comment by candrapersada** [comment]
`-f wv[fps>=30]+wa[abr>43]/wv+wa/w`
![gambar](https://user-images.githubusercontent.com/36833664/203487757-3d24b980-bd70-43d5-99cd-54d75726984e.png)
![gambar](https://user-images.githubusercontent.com/36833664/203487832-41bf6838-363a-48fe-b8a4-a6d18cf971f0.png)

**Comment by aandrew-me** [comment]
There is always the command line to use. The purpose of GUI is to make it easier for people.

**Comment by candrapersada** [comment]
![gambar](https://user-images.githubusercontent.com/36833664/203489082-7604aa2b-2cb8-4fa6-bb90-ed1b6b8e5460.png)
![gambar](https://user-images.githubusercontent.com/36833664/203489432-4ec6766f-9e4b-4cb0-8a08-7303bded2688.png)
