### ISSUE TITLE
select video quality from configuration file

### ISSUE THREAD

**Issue by candrapersada** [aandrew-me/ytDownloader#89]
is there any way to select video quality from config file
![video](https://user-images.githubusercontent.com/36833664/204123019-c4688be1-9a52-440f-83c8-b0b77509c6a4.PNG)
![video](https://user-images.githubusercontent.com/36833664/204123230-77040720-2870-474f-a06f-17d0b8159fce.PNG)

**Comment by aandrew-me** [comment]
Right now its not possible but it will be in next update. However if you don't want to wait, I have made a build for you. You can download from here -
https://filetransfer.io/data-package/u8nnsm96#link

**Comment by aandrew-me** [comment]
Anything else you have?

**Comment by candrapersada** [comment]
is there any way to select video quality from config file for video non playlists?
