### ISSUE TITLE
Add this app to winget, choco or scoop

### ISSUE THREAD

**Issue by CodeCubeNeo** [aandrew-me/ytDownloader#91]

**Comment by aandrew-me** [comment]
If its possible I will do it.
However there are 2 obstacles -
1. App is not signed
2. I don't use Windows

**Comment by aandrew-me** [comment]
I am trying to publish to chocolatey. But verification testing builds are failing. 

https://gist.github.com/choco-bot/50ebafa36cf836bfceb848099fef031d

**Comment by aandrew-me** [comment]
Builds are passing now

**Comment by aandrew-me** [comment]
App has been published to choco

It can be installed by the following command - 
`choco install ytdownloader`
