### ISSUE TITLE
Maybe add a web extension to download from yt

### ISSUE THREAD

**Issue by CodeCubeNeo** [aandrew-me/ytDownloader#92]
It would be easier to just click a button that says download in the webpage rather than copying a link. This is just an idea.

**Comment by aandrew-me** [comment]
I mean come on man! Don't be so lazy!

**Comment by aandrew-me** [comment]
I have plans to make the app appear in system tray which may help but I have no plans of making a browser extension

**Comment by CodeCubeNeo** [comment]
xd, just threw it in, to propose an idea for future dewelopment. Btw it isnt laziness if you download a lot of videos at once (like 100 or smth) it would really speed things up.

**Comment by aandrew-me** [comment]
> xd, just threw it in, to propose an idea for future dewelopment. Btw it isnt laziness if you download a lot of videos at once (like 100 or smth) it would really speed things up.

In that case you can save the links of the videos to a file and then download from the file 
`yt-dlp -a links.txt`
