### ISSUE TITLE
problem downloading since last, flatpak, update (2+days)

### ISSUE THREAD

**Issue by splace** [aandrew-me/ytDownloader#97]
get this...

![Screenshot from 2023-01-09 00-16-44](https://user-images.githubusercontent.com/1234848/211226541-e076ee09-f15b-445b-a227-bf4e7f0fd53b.png)

but found if i change download folder to the same folder? it then works...

![Screenshot from 2023-01-09 00-26-02](https://user-images.githubusercontent.com/1234848/211226546-8ed53b8c-51a8-47f5-bf58-5ddd1df9ee91.png)

**Comment by aandrew-me** [comment]
Hello.
Can you please provide more details. That download location in the first screenshot looks unusual. Did you choose it by yourself? Is it possible to reproduce the error as I couldn't reproduce it on my machine?

**Comment by splace** [comment]
OK, now not doing it, presume the 'change to the same folder' has fixed, but i did it several times previously, to other folders then back.

> that download location in the first screenshot looks unusual. Did you choose it by yourself?

a flatpak (on fedora silverblue) thing? always just used UI in app.

ill retry more tomorrow.

**Comment by splace** [comment]
used 4-5 times working fine!
