### ISSUE TITLE
No French translation

### ISSUE THREAD

**Issue by TitouanReal** [aandrew-me/ytDownloader#99]
I would like to help by providing a French translation, but as it is not on CrowdIn I can't. Could you add it so that I would be able to translate everything to French ?

**Comment by aandrew-me** [comment]
That's great! I have added it to crowdin. 
Also, what do French people call the French language?

**Comment by TitouanReal** [comment]
They call it "Français". Don't forget it is a ç and not a c : that's important !
Thank you

**Comment by aandrew-me** [comment]
Thank you!
I will definitely not forget!

**Comment by TitouanReal** [comment]
Everything is translated. Did my best to translate in context.

**Comment by aandrew-me** [comment]
Thank you very much for your efforts! I will add the translations to the app and French language will be available in the next update
